function loadIndex(){

  var index_code = ""
  +  "<div id='landing_body_background'>"
  +    "<div id='navbar'>"
  +      "<div id='burger_button_container'>"
  +        "<button type='button' class='toggler_btn' data-toggle='collapse' data-target='#mini_navbar' aria-expanded='false' aria-controls='mini_navbar'>"
  +          "<svg version='1.1' id='hamburger_icon' xmlns='http://www.w3.org/2000/svg' xmlns:xlink='http://www.w3.org/1999/xlink' x='0px' y='0px'"
  +              "viewBox='0 0 83.785 64.488' enable-background='new 0 0 83.785 64.488' xml:space='preserve'>"
  +          "<path d='M15.656,19.125H68.13c2.414,0,4.373-1.959,4.373-4.373s-1.959-4.373-4.373-4.373H15.656"
  +            "c-2.414,0-4.373,1.959-4.373,4.373S13.242,19.125,15.656,19.125z M68.13,27.871H15.656c-2.414,0-4.373,1.959-4.373,4.373"
  +            "c0,2.414,1.959,4.373,4.373,4.373H68.13c2.414,0,4.373-1.959,4.373-4.373C72.503,29.83,70.544,27.871,68.13,27.871z M68.13,45.363"
  +            "H15.656c-2.414,0-4.373,1.959-4.373,4.373s1.959,4.373,4.373,4.373H68.13c2.414,0,4.373-1.959,4.373-4.373"
  +            "S70.544,45.363,68.13,45.363z'/>"
  +          "</svg>"
  +      "</div>"
  +      "<div id='nav_options_container'>"
  +        "<div class='nav_options'>"
  +          "<a href='nosotros.html'>"
  +            "Nosotros"
  +         "</a>"
  +        "</div>"
  +        "<div class='nav_options'>"
  +          "<a href='nuestros_vinos.html'>"
  +            "Nuestos Vinos"
  +          "</a>"
  +        "</div>"
  +        "<div id='center_logo_container'>"
  +          "<a href='index.html'>"
  +          "<img src='images/logoBlanco.svg' alt='Logo Vinícola Retorno' id='center_logo'>"
  +          "</a>"
  +        "</div>"
  +        "<div class='nav_options'>"
  +          "<a href='puntos_venta.html'>"
  +           "Puntos de Venta"
  +          "</a>"
  +        "</div>"
  +        "<div class='nav_options'>"
  +          "<a href='visitanos.html'>"
  +            "Visítanos"
  +          "</a>"
  +        "</div>"
  +      "</div>"
  +      "<div class='collapse' id='mini_navbar'>"
  +        "<div class='option_mini_navbar' id='active'>"
  +          "<a href='index.html'>"
  +            "Inicio"
  +          "</a>"
  +        "</div>"
  +        "<div class='option_mini_navbar'>"
  +          "<a href='nosotros.html'>"
  +            "Nosotros"
  +          "</a>"
  +        "</div>"
  +        "<div class='option_mini_navbar'>"
  +          "<a href='nuestros_vinos.html'>"
  +            "Nuestos Vinos"
  +          "</a>"
  +        "</div>"
  +        "<div class='option_mini_navbar'>"
  +          "<a href='puntos_venta.html'>"
  +            "Puntos de Venta"
  +          "</a>"
  +        "</div>"
  +        "<div class='option_mini_navbar'>"
  +          "<a href='visitanos.html'>"
  +            "Visítanos"
  +          "</a>"
  +        "</div>"
  +      "</div>"
  +    "</div>"
  +    "<div id='mid_image_text'>"
  +      "<div class='mid_image_text_container' id='primary_mid_text'>"
  +        "Auténtica expresión del terruño y respeto a la naturaleza"
  +      "</div>"
  +    "</div>"
  +  "</div>"
  +  "<div id='footer'>"
  +    "<div id='footer_options_container'>"
  +      "<div class='footer_option' id='left_option'>"
  +        "<a href='index.html'>"
  +          "<img src='images/logoBlanco.svg' alt='Logo Vinícola Retorno' id='logo_footer'>"
  +        "</a>"
  +        "<div id='vinicola_legal'>"
  +          "<a href='index.html'>"
  +           "© Copyright <br>"
  +            "Vinícola Retorno S.A. de C.V."
  +          "</a>"
  +        "</div>"
  +      "</div>"
  +      "<div class='footer_option' id='center_option'>"
  +        "<div class='footer_headline'>"
  +          "<a href='visitanos.html'>"
  +            "Contactanos"
  +          "</a>"
  +        "</div>"
  +        "<div class='info_cities'>"
  +          "CDMX"
  +        "</div>"
  +          "<a href='tel:+525555284733'>"
  +            "55-28-47-33"
  +          "</a>"
  +        "<div class='info_cities'>"
  +          "Valle de Guadalupe"
  +        "</div>"
  +          "<a href='tel:+5216461519247'>"
  +            "646-151-92-47<br>"
  +          "</a>"
  +          "<a href='mailto:info@vinicolaretorno.com'>"
  +            "info@vinicolaretorno.com"
  +          "</a>"
  +      "</div>"
  +      "<div class='footer_option' id='center_option'>"
  +        "<div class='footer_headline'>"
  +          "<a href='visitanos.html'>"
  +            "Visítanos"
  +          "</a>"
  +        "</div>"
  +        "<div id='info_visit'>"
  +          "Todos los dias <br>"
  +          "11:00 AM - 5:00 PM <br>"
  +          "<div id='info_address'>"
  +            "Santos Degollado #161, San Antonio de las Minas,"
  +            " C.P. 22766, Ensenada, BC."
  +          "</div>"
  +        "</div>"
  +      "</div>"
  +      "<div class='footer_option' id='right_option'>"
  +        "<div class='footer_headline'>"
  +          "<a href='visitanos.html'>"
  +            "Síguenos"
  +          "</a>"
  +        "</div>"
  +        "<div id='social_media_container'>"
  +          "<div class='social_media'>"
  +            "<a href='https://www.facebook.com/vinicolaretorno/'>"
  +              "<img src='images/facebook.svg' alt='Facebook Vinícola Retorno' class='social_media'>"
  +            "</a>"
  +          "</div>"
  +          "<div class='social_media'>"
  +            "<a href='https://twitter.com/vinicolaretorno'>"
  +              "<img src='images/twitter.svg' alt='Twitter Vinícola Retorno' class='social_media'>"
  +            "</a>"
  +          "</div>"
  +          "<div class='social_media'>"
  +            "<a href='https://www.instagram.com/vinicolaretorno/'>"
  +              "<img src='images/instagram.svg' alt='Instagram Vinícola Retorno' class='social_media'>"
  +            "</a>"
  +          "</div>"
  +        "</div>"
  +      "</div>"
  +    "</div>"
  +  "</div>"
;
  document.getElementById("index_page").innerHTML = "";
  document.getElementById("index_page").innerHTML = index_code;
}

function loadNosotros(){

  var nosotros_code = ""
  +  "<div class='body_background' id='nosotros_background'>"
  +    "<div id='navbar'>"
  +      "<div id='burger_button_container'>"
  +        "<button type='button' class='toggler_btn' data-toggle='collapse' data-target='#mini_navbar' aria-expanded='false' aria-controls='mini_navbar'>"
  +          "<svg version='1.1' id='hamburger_icon' xmlns='http://www.w3.org/2000/svg' xmlns:xlink='http://www.w3.org/1999/xlink' x='0px' y='0px'"
  +              "viewBox='0 0 83.785 64.488' enable-background='new 0 0 83.785 64.488' xml:space='preserve'>"
  +          "<path d='M15.656,19.125H68.13c2.414,0,4.373-1.959,4.373-4.373s-1.959-4.373-4.373-4.373H15.656"
  +            "c-2.414,0-4.373,1.959-4.373,4.373S13.242,19.125,15.656,19.125z M68.13,27.871H15.656c-2.414,0-4.373,1.959-4.373,4.373"
  +            "c0,2.414,1.959,4.373,4.373,4.373H68.13c2.414,0,4.373-1.959,4.373-4.373C72.503,29.83,70.544,27.871,68.13,27.871z M68.13,45.363"
  +            "H15.656c-2.414,0-4.373,1.959-4.373,4.373s1.959,4.373,4.373,4.373H68.13c2.414,0,4.373-1.959,4.373-4.373"
  +            "S70.544,45.363,68.13,45.363z'/>"
  +          "</svg>"
  +      "</div>"
  +      "<div id='nav_options_container'>"
  +        "<div class='nav_options' id='active_nav'>"
  +          "<a href='nosotros.html'>"
  +            "Nosotros"
  +         "</a>"
  +        "</div>"
  +        "<div class='nav_options'>"
  +          "<a href='nuestros_vinos.html'>"
  +            "Nuestos Vinos"
  +          "</a>"
  +        "</div>"
  +        "<div id='center_logo_container'>"
  +          "<a href='index.html'>"
  +          "<img src='images/logoBlanco.svg' alt='Logo Vinícola Retorno' id='center_logo'>"
  +          "</a>"
  +        "</div>"
  +        "<div class='nav_options'>"
  +          "<a href='puntos_venta.html'>"
  +           "Puntos de Venta"
  +          "</a>"
  +        "</div>"
  +        "<div class='nav_options'>"
  +          "<a href='visitanos.html'>"
  +            "Visítanos"
  +          "</a>"
  +        "</div>"
  +      "</div>"
  +      "<div class='collapse' id='mini_navbar'>"
  +        "<div class='option_mini_navbar'>"
  +          "<a href='index.html'>"
  +            "Inicio"
  +          "</a>"
  +        "</div>"
  +        "<div class='option_mini_navbar' id='active'>"
  +          "<a href='nosotros.html'>"
  +            "Nosotros"
  +          "</a>"
  +        "</div>"
  +        "<div class='option_mini_navbar'>"
  +          "<a href='nuestros_vinos.html'>"
  +            "Nuestos Vinos"
  +          "</a>"
  +        "</div>"
  +        "<div class='option_mini_navbar'>"
  +          "<a href='puntos_venta.html'>"
  +            "Puntos de Venta"
  +          "</a>"
  +        "</div>"
  +        "<div class='option_mini_navbar'>"
  +          "<a href='visitanos.html'>"
  +            "Visítanos"
  +          "</a>"
  +        "</div>"
  +      "</div>"
  +    "</div>"
  +    "<div id='sec_mid_image_text'>"
  +      "<div class='mid_image_text_container' id='sec_mid_text'>"
  +        "Nosotros"
  +      "</div>"
  +    "</div>"
  +   "</div>"
  +   "<div id='main_body_container'>"
  +     "<div id='main_body_title'>"
  +       "Vinícola Retorno"
  +     "</div>"
  +   "<div id='main_body'>"
  +    "<div class='our_story_container'>"
  +      "<div class='our_story_row'>"
  +        "<div class='our_story_txt'>"
  +          "Vinícola Retorno es un proyecto familiar creado en el año 2008 por el productor"
  +          " Adrián García. Nuestra cava está ubicada en San Antonio de las Minas, dentro del"
  +          " Valle de Guadalupe en el municipio de Ensenada.<br>"
  +          "<br>"
  +          "La construcción de sus muros fue realizada con pacas de paja y lodo, de manera que"
  +          " refleja la filosofía de respetar al máximo el paisaje y el medio ambiente. Además"
  +          " de la conservación, la vinícola fue diseñada de tal manera para crear un espacio"
  +          " fresco ideal para el cuidado de los vinos de manera natural en un ambiente sencillo"
  +          " y armonioso.<br>"
  +        "</div>"
  +        "<div class='our_story_img' id='our_story_img_1'>"
  +        "</div>"
  +      "</div>"
  +      "<div class='our_story_row' id='invert_breakpoint'>"
  +        "<div class='our_story_img' id='our_story_img_2'>"
  +        "</div>"
  +        "<div class='our_story_txt' >"
  +         "Nuestros vinos reflejan las características intrínsecas del terruño bajacaliforniano"
  +          " ya que todos los caldos producidos en Vinícola Retorno destacan por su meticulosa elaboración"
  +          " y por no estar sujetos a ninguna corrección artificial  de acidez, ni de azúcar. <br>"
  +          "<br>"
  +          "Las variedades de uva que utilizamos para la realización de cada una de nuestras"
  +          " etiquetas provienen de vides antiguas de temporal, por lo que normalmente obtenemos"
  +          " mostos muy concentrados que presentan aromas y sabores únicos en cada añada. <br>"
  +        "</div>"
  +      "</div>"
  +    "</div>"
  +    "<div class='our_story_row' >"
  +      "<div class='our_story_txt' id='no_center'>"
  +        "En la actualidad, la producción anual de Vinícola Retorno asciende a aproximadamente"
  +        " dos mil quinientas cajas de vino que se presentan en nuestras etiquetas: Parábola Blanco, TeO, Pluchas,"
  +        " Parábola, Palabra, Homenaje, Retorno  y Década.<br>"
  +        "<br>"
  +        "Aventúrese a descubrir las delicias que el terruño bajacaliforniano tiene para ofrecerle"
  +        " en Vinícola Retorno."
  +      "</div>"
  +      "<div class='our_story_img' id='our_story_img_3'>"
  +      "</div>"
  +    "</div>"
  +  "</div>"
  +  "</div>"
  +  "<div id='footer'>"
  +    "<div id='footer_options_container'>"
  +      "<div class='footer_option' id='left_option'>"
  +        "<a href='index.html'>"
  +          "<img src='images/logoBlanco.svg' alt='Logo Vinícola Retorno' id='logo_footer'>"
  +        "</a>"
  +        "<div id='vinicola_legal'>"
  +          "<a href='index.html'>"
  +           "© Copyright <br>"
  +            "Vinícola Retorno S.A. de C.V."
  +          "</a>"
  +        "</div>"
  +      "</div>"
  +      "<div class='footer_option' id='center_option'>"
  +        "<div class='footer_headline'>"
  +          "<a href='visitanos.html'>"
  +            "Contactanos"
  +          "</a>"
  +        "</div>"
  +        "<div class='info_cities'>"
  +          "CDMX"
  +        "</div>"
  +          "<a href='tel:+525555284733'>"
  +            "55-28-47-33"
  +          "</a>"
  +        "<div class='info_cities'>"
  +          "Valle de Guadalupe"
  +        "</div>"
  +          "<a href='tel:+5216461519247'>"
  +            "646-151-92-47<br>"
  +          "</a>"
  +          "<a href='mailto:info@vinicolaretorno.com'>"
  +            "info@vinicolaretorno.com"
  +          "</a>"
  +      "</div>"
  +      "<div class='footer_option' id='center_option'>"
  +        "<div class='footer_headline'>"
  +          "<a href='visitanos.html'>"
  +            "Visítanos"
  +          "</a>"
  +        "</div>"
  +        "<div id='info_visit'>"
  +          "Todos los dias <br>"
  +          "11:00 AM - 5:00 PM <br>"
  +          "<div id='info_address'>"
  +            "Santos Degollado #161, San Antonio de las Minas,"
  +            " C.P. 22766, Ensenada, BC."
  +          "</div>"
  +        "</div>"
  +      "</div>"
  +      "<div class='footer_option' id='right_option'>"
  +        "<div class='footer_headline'>"
  +          "<a href='visitanos.html'>"
  +            "Síguenos"
  +          "</a>"
  +        "</div>"
  +        "<div id='social_media_container'>"
  +          "<div class='social_media'>"
  +            "<a href='https://www.facebook.com/vinicolaretorno/'>"
  +              "<img src='images/facebook.svg' alt='Facebook Vinícola Retorno' class='social_media'>"
  +            "</a>"
  +          "</div>"
  +          "<div class='social_media'>"
  +            "<a href='https://twitter.com/vinicolaretorno'>"
  +              "<img src='images/twitter.svg' alt='Twitter Vinícola Retorno' class='social_media'>"
  +            "</a>"
  +          "</div>"
  +          "<div class='social_media'>"
  +            "<a href='https://www.instagram.com/vinicolaretorno/'>"
  +              "<img src='images/instagram.svg' alt='Instagram Vinícola Retorno' class='social_media'>"
  +            "</a>"
  +          "</div>"
  +        "</div>"
  +      "</div>"
  +    "</div>"
  +  "</div>"
;
  document.getElementById("nosotros_page").innerHTML = "";
  document.getElementById("nosotros_page").innerHTML = nosotros_code;
}

function loadNuestrosVinos() {

  var nuestros_vinos_code= ""
  +  "<div class='body_background' id='vinos_background'>"
  +    "<div id='navbar'>"
  +      "<div id='burger_button_container'>"
  +        "<button type='button' class='toggler_btn' data-toggle='collapse' data-target='#mini_navbar' aria-expanded='false' aria-controls='mini_navbar'>"
  +          "<svg version='1.1' id='hamburger_icon' xmlns='http://www.w3.org/2000/svg' xmlns:xlink='http://www.w3.org/1999/xlink' x='0px' y='0px'"
  +              "viewBox='0 0 83.785 64.488' enable-background='new 0 0 83.785 64.488' xml:space='preserve'>"
  +          "<path d='M15.656,19.125H68.13c2.414,0,4.373-1.959,4.373-4.373s-1.959-4.373-4.373-4.373H15.656"
  +            "c-2.414,0-4.373,1.959-4.373,4.373S13.242,19.125,15.656,19.125z M68.13,27.871H15.656c-2.414,0-4.373,1.959-4.373,4.373"
  +            "c0,2.414,1.959,4.373,4.373,4.373H68.13c2.414,0,4.373-1.959,4.373-4.373C72.503,29.83,70.544,27.871,68.13,27.871z M68.13,45.363"
  +            "H15.656c-2.414,0-4.373,1.959-4.373,4.373s1.959,4.373,4.373,4.373H68.13c2.414,0,4.373-1.959,4.373-4.373"
  +            "S70.544,45.363,68.13,45.363z'/>"
  +          "</svg>"
  +      "</div>"
  +      "<div id='nav_options_container'>"
  +        "<div class='nav_options'>"
  +          "<a href='nosotros.html'>"
  +            "Nosotros"
  +         "</a>"
  +        "</div>"
  +        "<div class='nav_options' id='active_nav'>"
  +          "<a href='nuestros_vinos.html'>"
  +            "Nuestos Vinos"
  +          "</a>"
  +        "</div>"
  +        "<div id='center_logo_container'>"
  +          "<a href='index.html'>"
  +          "<img src='images/logoBlanco.svg' alt='Logo Vinícola Retorno' id='center_logo'>"
  +          "</a>"
  +        "</div>"
  +        "<div class='nav_options'>"
  +          "<a href='puntos_venta.html'>"
  +           "Puntos de Venta"
  +          "</a>"
  +        "</div>"
  +        "<div class='nav_options'>"
  +          "<a href='visitanos.html'>"
  +            "Visítanos"
  +          "</a>"
  +        "</div>"
  +      "</div>"
  +      "<div class='collapse' id='mini_navbar'>"
  +        "<div class='option_mini_navbar'>"
  +          "<a href='index.html'>"
  +            "Inicio"
  +          "</a>"
  +        "</div>"
  +        "<div class='option_mini_navbar'>"
  +          "<a href='nosotros.html'>"
  +            "Nosotros"
  +          "</a>"
  +        "</div>"
  +        "<div class='option_mini_navbar' id='active'>"
  +          "<a href='nuestros_vinos.html'>"
  +            "Nuestos Vinos"
  +          "</a>"
  +        "</div>"
  +        "<div class='option_mini_navbar'>"
  +          "<a href='puntos_venta.html'>"
  +            "Puntos de Venta"
  +          "</a>"
  +        "</div>"
  +        "<div class='option_mini_navbar'>"
  +          "<a href='visitanos.html'>"
  +            "Visítanos"
  +          "</a>"
  +        "</div>"
  +      "</div>"
  +    "</div>"
  +    "<div id='sec_mid_image_text'>"
  +      "<div class='mid_image_text_container' id='sec_mid_text'>"
  +       "Nuestros Vinos"
  +      "</div>"
  +    "</div>"
  +   "</div>"
  +   "<div id='main_body_container'>"
  +    "<div id='main_body_title'>"
  +      "Nuestras Etiquetas"
  +    "</div>"
  +    "<div id='main_body'>"
  +      "<div id='all_bottle_container'>"
  +        "<div class='winetype' id='white'>"
  +          "<div class='winetype_name'>"
  +            "Blancos"
  +          "</div>"
  +            "<div class='winetype_bottle_container'>"
  +              "<div class='bottle_container'>"
  +                  "<img src='images/parabolaBlancoIcn.png' alt='Botella de Vino Blanco Parábola' class='bottle' onclick='parabolaBlanco()'>"
  +                "<div class='wine_name'>"
  +                  "Parábola <br>"
  +                  "Blanco"
  +                "</div>"
  +              "</div>"
  +              "<div class='bottle_container'>"
  +                "<img src='images/teoIcn.png' alt='Botella de Vino Blanco TeO' class='bottle' onclick='teo()'>"
  +                "<div class='wine_name'>"
  +                  "TeO"
  +                "</div>"
  +              "</div>"
  +            "</div>"
  +        "</div>"
  +        "<div class='winetype' id='rose'>"
  +          "<div class='winetype_name'>"
  +            "Rosados"
  +          "</div>"
  +          "<div class='winetype_bottle_container'>"
  +            "<div class='bottle_container'>"
  +              "<img src='images/piluchasIcn.png' alt='Botella de Vino Rosado Piluchas' class='bottle' onclick='piluchas()'>"
  +              "<div class='wine_name'>"
  +                "Piluchas"
  +              "</div>"
  +            "</div>"
  +          "</div>"
  +        "</div>"
  +        "<div class='winetype' id='red'>"
  +          "<div class='winetype_name'>"
  +            "Tintos"
  +          "</div>"
  +          "<div class='winetype_bottle_container'>"
  +            "<div class='bottle_container'>"
  +              "<img src='images/parabolaIcn.png' alt='Botella de Vino Tinto Parábola' class='bottle' onclick='parabola()'>"
  +              "<div class='wine_name'>"
  +                "Parábola"
  +              "</div>"
  +            "</div>"
  +            "<div class='bottle_container'>"
  +              "<img src='images/palabraIcn.png' alt='Botella de Vino Tinto Palabra' class='bottle'onclick='palabra()'>"
  +              "<div class='wine_name'>"
  +                "Palabra"
  +              "</div>"
  +            "</div>"
  +            "<div class='bottle_container'>"
  +              "<img src='images/homenajeIcn.png' alt='Botella de Vino Tinto Homenaje' class='bottle' onclick='homenaje()'>"
  +              "<div class='wine_name'>"
  +                "Homenaje"
  +              "</div>"
  +            "</div>"
  +            "<div class='bottle_container'>"
  +              "<img src='images/retornoIcn.png' alt='Botella de Vino Tinto Retorno' class='bottle' onclick='retorno()'>"
  +              "<div class='wine_name'>"
  +                "Retorno"
  +              "</div>"
  +            "</div>"
  +            "<div class='bottle_container'>"
  +              "<img src='images/decadaIcn.png' alt='Botella de Vino Tinto Década' class='bottle' onclick='decada()'>"
  +              "<div class='wine_name'>"
  +                "Década"
  +              "</div>"
  +            "</div>"
  +          "</div>"
  +        "</div>"
  +      "</div>"
  +      "<div id='main_wine_container'>"
  +      "</div>"
  +      "<div id='breakpoint_all_bottle_container'>"
  +        "<div class='winetype' id='white'>"
  +          "<div class='winetype_name'>"
  +            "Blancos"
  +          "</div>"
  +            "<div class='winetype_bottle_container'>"
  +              "<div class='bottle_container'>"
  +                  "<img src='images/parabolaBlancoIcn.png' alt='Botella de Vino Blanco Parábola' class='bottle' onclick='parabolaBlancoExpand()'>"
  +                "<div class='wine_name' onclick='parabolaBlancoExpand()'>"
  +                  "Parábola Blanco"
  +                "</div>"
  +                "<div class='wine_expand_container' id='parabola_blanco_expand'>"
  +                "</div>"
  +              "</div>"
  +              "<div class='bottle_container'>"
  +                "<img src='images/teoIcn.png' alt='Botella de Vino Blanco TeO' class='bottle' onclick='teoExpand()'>"
  +                "<div class='wine_name' onclick='teoExpand()'>"
  +                  "TeO"
  +                "</div>"
  +                "<div class='wine_expand_container' id='teo_expand'>"
  +                "</div>"
  +              "</div>"
  +            "</div>"
  +        "</div>"
  +        "<div class='winetype' id='rose'>"
  +          "<div class='winetype_name'>"
  +            "Rosados"
  +          "</div>"
  +          "<div class='winetype_bottle_container'>"
  +            "<div class='bottle_container'>"
  +              "<img src='images/piluchasIcn.png' alt='Botella de Vino Rosado Piluchas' class='bottle' onclick='piluchasExpand()'>"
  +              "<div class='wine_name' onclick='piluchasExpand()'>"
  +                "Piluchas"
  +              "</div>"
  +              "<div class='wine_expand_container' id='piluchas_expand'>"
  +              "</div>"
  +            "</div>"
  +          "</div>"
  +        "</div>"
  +        "<div class='winetype' id='red'>"
  +          "<div class='winetype_name'>"
  +            "Tintos"
  +          "</div>"
  +          "<div class='winetype_bottle_container'>"
  +            "<div class='bottle_container'>"
  +              "<img src='images/parabolaIcn.png' alt='Botella de Vino Tinto Parábola' class='bottle' onclick='parabolaExpand()'>"
  +              "<div class='wine_name' onclick='parabolaExpand()'>"
  +                "Parábola"
  +              "</div>"
  +              "<div class='wine_expand_container' id='parabola_expand'>"
  +              "</div>"
  +            "</div>"
  +            "<div class='bottle_container'>"
  +              "<img src='images/palabraIcn.png' alt='Botella de Vino Tinto Palabra' class='bottle' onclick='palabraExpand()'>"
  +              "<div class='wine_name' onclick='palabraExpand()'>"
  +                "Palabra"
  +              "</div>"
  +              "<div class='wine_expand_container' id='palabra_expand'>"
  +              "</div>"
  +            "</div>"
  +            "<div class='bottle_container'>"
  +              "<img src='images/homenajeIcn.png' alt='Botella de Vino Tinto Homenaje' class='bottle' onclick='homenajeExpand()'>"
  +              "<div class='wine_name' onclick='homenajeExpand()'>"
  +                "Homenaje"
  +              "</div>"
  +              "<div class='wine_expand_container' id='homenaje_expand'>"
  +              "</div>"
  +            "</div>"
  +            "<div class='bottle_container'>"
  +              "<img src='images/retornoIcn.png' alt='Botella de Vino Tinto Retorno' class='bottle' onclick='retornoExpand()'>"
  +              "<div class='wine_name' onclick='retornoExpand()'>"
  +                "Retorno"
  +              "</div>"
  +              "<div class='wine_expand_container' id='retorno_expand'>"
  +              "</div>"
  +            "</div>"
  +            "<div class='bottle_container'>"
  +              "<img src='images/decadaIcn.png' alt='Botella de Vino Tinto Década' class='bottle' onclick='decadaExpand()'>"
  +              "<div class='wine_name' onclick='decadaExpand()'>"
  +                "Década"
  +              "</div>"
  +              "<div class='wine_expand_container' id='decada_expand'>"
  +              "</div>"
  +            "</div>"
  +          "</div>"
  +        "</div>"
  +      "</div>"
  +    "</div>"
  +   "</div>"
  +  "<div id='footer'>"
  +    "<div id='footer_options_container'>"
  +      "<div class='footer_option' id='left_option'>"
  +        "<a href='index.html'>"
  +          "<img src='images/logoBlanco.svg' alt='Logo Vinícola Retorno' id='logo_footer'>"
  +        "</a>"
  +        "<div id='vinicola_legal'>"
  +          "<a href='index.html'>"
  +           "© Copyright <br>"
  +            "Vinícola Retorno S.A. de C.V."
  +          "</a>"
  +        "</div>"
  +      "</div>"
  +      "<div class='footer_option' id='center_option'>"
  +        "<div class='footer_headline'>"
  +          "<a href='visitanos.html'>"
  +            "Contactanos"
  +          "</a>"
  +        "</div>"
  +        "<div class='info_cities'>"
  +          "CDMX"
  +        "</div>"
  +          "<a href='tel:+525555284733'>"
  +            "55-28-47-33"
  +          "</a>"
  +        "<div class='info_cities'>"
  +          "Valle de Guadalupe"
  +        "</div>"
  +          "<a href='tel:+5216461519247'>"
  +            "646-151-92-47<br>"
  +          "</a>"
  +          "<a href='mailto:info@vinicolaretorno.com'>"
  +            "info@vinicolaretorno.com"
  +          "</a>"
  +      "</div>"
  +      "<div class='footer_option' id='center_option'>"
  +        "<div class='footer_headline'>"
  +          "<a href='visitanos.html'>"
  +            "Visítanos"
  +          "</a>"
  +        "</div>"
  +        "<div id='info_visit'>"
  +          "Todos los dias <br>"
  +          "11:00 AM - 5:00 PM <br>"
  +          "<div id='info_address'>"
  +            "Santos Degollado #161, San Antonio de las Minas,"
  +            " C.P. 22766, Ensenada, BC."
  +          "</div>"
  +        "</div>"
  +      "</div>"
  +      "<div class='footer_option' id='right_option'>"
  +        "<div class='footer_headline'>"
  +          "<a href='visitanos.html'>"
  +            "Síguenos"
  +          "</a>"
  +        "</div>"
  +        "<div id='social_media_container'>"
  +          "<div class='social_media'>"
  +            "<a href='https://www.facebook.com/vinicolaretorno/'>"
  +              "<img src='images/facebook.svg' alt='Facebook Vinícola Retorno' class='social_media'>"
  +            "</a>"
  +          "</div>"
  +          "<div class='social_media'>"
  +            "<a href='https://twitter.com/vinicolaretorno'>"
  +              "<img src='images/twitter.svg' alt='Twitter Vinícola Retorno' class='social_media'>"
  +            "</a>"
  +          "</div>"
  +          "<div class='social_media'>"
  +            "<a href='https://www.instagram.com/vinicolaretorno/'>"
  +              "<img src='images/instagram.svg' alt='Instagram Vinícola Retorno' class='social_media'>"
  +            "</a>"
  +          "</div>"
  +        "</div>"
  +      "</div>"
  +    "</div>"
  +  "</div>"
;
  document.getElementById("nuestros_vinos_page").innerHTML = "";
  document.getElementById("nuestros_vinos_page").innerHTML = nuestros_vinos_code;
}

function parabolaBlanco(){

  var parabola_blanco_info = ""
  +"<div class='main_bottle_container'>"
  +  "<img src='images/parabolaBlancoMain.png' class='main_bottle_container' alt='' >"
  +"</div>"
  +"<div id='text_wine_container'>"
  +  "<div id='main_wine_name'>"
  +    "Parábola Blanco"
  +  "</div>"
  +  "<div id='wine_tech_container'>"
  +    "<div id='wine_tech_header' class='wine_header'>"
  +      "Ficha técnica"
  +    "</div>"
  +    "<div id='wine_tech_txt' class='wine_txt'>"
  +      "<b>Clasificación:</b> Blanco <br>"
  +      "<b>Región:</b> San Antonio de las Minas, Valle de Guadalupe <br>"
  +      "<b>Añejamiento:</b> Fermentado y reposado en tanques de acero inoxidable <br>"
  +      "<b>Variedad:</b> Chenin Blanc <br>"
  +      "<b>Cosecha:</b> 2017 <br>"
  +    "</div>"
  +  "</div>"
  +  "<div id='wine_notes_container'>"
  +    "<div id='wine_notes_header' class='wine_header'>"
  +      "Nota de cata"
  +    "</div>"
  +    "<div id='wine_notes_txt' class='wine_txt'>"
  +      "<b>Vista:</b> De color amarillo paja con brillos dorados y verdes en el ribete <br>"
  +      "<b>Nariz:</b> Aromas a flores blancas y cítricos, entre los que destacan"
  +      " la toronja y limón amarillo <br>"
  +      "<b>Boca:</b> Ligero y agradable, con un ataque franco y una acidez  balanceada"
  +      " acompañada de sabores frutales en el retrogusto  <br>"
  +    "</div>"
  +  "</div>"
  +  "<div id='wine_marriage_container'>"
  +    "<div id='wine_marriage_header' class='wine_header'>"
  +      "Maridaje"
  +    "</div>"
  +    "<div id='wine_marriage_txt' class='wine_txt'>"
  +      "Ideal  para armonizar todo tipo de pescados, pastas"
  +      " cremosas, pizzas y quesos de intensidad media. <br>"
  +      "<br>"
  +      "Temperatura de servicio de 8º a 10º C."
  +    "</div>"
  +  "</div>"
  +  "<div id='wine_corrections' class='wine_txt'>"
  +    "Vino sin correcciones químicas"
  +  "</div>"
  +"</div>"
  ;

  document.getElementById("main_wine_container").innerHTML = "";
  document.getElementById("main_wine_container").innerHTML = parabola_blanco_info;
  document.getElementById('main_wine_container').scrollIntoView({ behavior: 'smooth', block: 'end' });
}

function teo(){

  var teo_info = ""
  +"<div class='main_bottle_container'>"
  +  "<img src='images/teoMain.png' class='main_bottle_container' alt='' >"
  +"</div>"
  +"<div id='text_wine_container'>"
  +  "<div id='main_wine_name'>"
  +    "TeO"
  +  "</div>"
  +  "<div id='wine_tech_container'>"
  +    "<div id='wine_tech_header' class='wine_header'>"
  +      "Ficha técnica"
  +    "</div>"
  +    "<div id='wine_tech_txt' class='wine_txt'>"
  +      "<b>Clasificación:</b> Blanco <br>"
  +      "<b>Región:</b> San Antonio de las Minas, Valle de Guadalupe <br>"
  +      "<b>Añejamiento:</b> Reposado 8 meses en barricas de roble blanco <br>"
  +      "<b>Variedad:</b> Chenin Blanc y Chardonay <br>"
  +      "<b>Cosecha:</b> 2016 <br>"
  +    "</div>"
  +  "</div>"
  +  "<div id='wine_notes_container'>"
  +    "<div id='wine_notes_header' class='wine_header'>"
  +      "Nota de cata"
  +    "</div>"
  +    "<div id='wine_notes_txt' class='wine_txt'>"
  +      "<b>Vista:</b> De color amarillo paja con brillos verdes en el ribete <br>"
  +      "<b>Nariz:</b> Aromas que recuerdan a la piña, guayaba, durazno y la miel,"
  +      " sobre un fondo a pan tostado, madera y mantequilla <br>"
  +      "<b>Boca:</b> Cuerpo medio con una acidez balanceada y un retrogusto de"
  +      " frutas tropicales con notas a cacao <br>"
  +    "</div>"
  +  "</div>"
  +  "<div id='wine_marriage_container'>"
  +    "<div id='wine_marriage_header' class='wine_header'>"
  +      "Maridaje"
  +    "</div>"
  +    "<div id='wine_marriage_txt' class='wine_txt'>"
  +      "Ideal como aperitivo, para acompañar pescados y mariscos,"
  +      " quesos de intensidad media, pastas cremosas y pizza <br>"
  +      "<br>"
  +      "Temperatura de servicio de 8º a 10º C."
  +    "</div>"
  +  "</div>"
  +  "<div id='wine_corrections' class='wine_txt'>"
  +    "Vino sin correcciones químicas"
  +  "</div>"
  +"</div>"
  ;

  document.getElementById("main_wine_container").innerHTML = "";
  document.getElementById("main_wine_container").innerHTML = teo_info;
  document.getElementById('main_wine_container').scrollIntoView({ behavior: 'smooth', block: 'end' });
}

function piluchas(){

  var piluchas_info = ""
  +"<div class='main_bottle_container'>"
  +  "<img src='images/piluchasMain.png' class='main_bottle_container' alt='' >"
  +"</div>"
  +"<div id='text_wine_container'>"
  +  "<div id='main_wine_name'>"
  +    "Piluchas"
  +  "</div>"
  +  "<div id='wine_tech_container'>"
  +    "<div id='wine_tech_header' class='wine_header'>"
  +      "Ficha técnica"
  +    "</div>"
  +    "<div id='wine_tech_txt' class='wine_txt'>"
  +      "<b>Clasificación:</b> Rosado <br>"
  +      "<b>Región:</b> San Antonio de las Minas, Valle de Guadalupe <br>"
  +      "<b>Añejamiento:</b> Fermentado y reposado en tanques de acero inoxidable <br>"
  +      "<b>Variedad:</b> Grenache, Barbera, Zinfandel y Tempranillo <br>"
  +      "<b>Cosecha:</b> 2017 <br>"
  +    "</div>"
  +  "</div>"
  +  "<div id='wine_notes_container'>"
  +    "<div id='wine_notes_header' class='wine_header'>"
  +      "Nota de cata"
  +    "</div>"
  +    "<div id='wine_notes_txt' class='wine_txt'>"
  +      "<b>Vista:</b> De color rojo claro con brillos violaceos en el ribete <br>"
  +      "<b>Nariz:</b> Aromas a fresas, toronja, flores de azahar y jazmín <br>"
  +      "<b>Boca:</b> Potente y fresco, con un retrogusto muy prolongado <br>"
  +    "</div>"
  +  "</div>"
  +  "<div id='wine_marriage_container'>"
  +    "<div id='wine_marriage_header' class='wine_header'>"
  +      "Maridaje"
  +    "</div>"
  +    "<div id='wine_marriage_txt' class='wine_txt'>"
  +      "Ideal como aperitivo, para acompañar pescados y mariscos,"
  +      " así como carnes blancas y pastas <br>"
  +      "<br>"
  +      "Temperatura de servicio de 8º a 10º C."
  +    "</div>"
  +  "</div>"
  +  "<div id='wine_corrections' class='wine_txt'>"
  +    "Vino sin correcciones químicas"
  +  "</div>"
  +"</div>"
  ;

  document.getElementById("main_wine_container").innerHTML = "";
  document.getElementById("main_wine_container").innerHTML = piluchas_info;
  document.getElementById('main_wine_container').scrollIntoView({ behavior: 'smooth', block: 'end' });
}

function parabola(){

  var parabola_info = ""
  +"<div class='main_bottle_container'>"
  +  "<img src='images/parabolaMain.png' class='main_bottle_container' alt='' >"
  +"</div>"
  +"<div id='text_wine_container'>"
  +  "<div id='main_wine_name'>"
  +    "Parábola"
  +  "</div>"
  +  "<div id='wine_tech_container'>"
  +    "<div id='wine_tech_header' class='wine_header'>"
  +      "Ficha técnica"
  +    "</div>"
  +    "<div id='wine_tech_txt' class='wine_txt'>"
  +      "<b>Clasificación:</b> Tinto <br>"
  +      "<b>Región:</b> San Antonio de las Minas, Valle de Guadalupe <br>"
  +      "<b>Añejamiento:</b> 6 meses en barrica de roble blanco <br>"
  +      "<b>Variedad:</b> Tempranillo 50% y Barbera 50% <br>"
  +      "<b>Cosecha:</b> 2016 <br>"
  +    "</div>"
  +  "</div>"
  +  "<div id='wine_notes_container'>"
  +    "<div id='wine_notes_header' class='wine_header'>"
  +      "Nota de cata"
  +    "</div>"
  +    "<div id='wine_notes_txt' class='wine_txt'>"
  +      "<b>Vista:</b> De color rojorubí con algúnos brillos violáceos en el ribete <br>"
  +      "<b>Nariz:</b> Aromas que recuerdan la fruta madura, como las fresas y las frambuesas,"
  +      " así como algunas notas a tabaco, café cacao y madera <br>"
  +      "<b>Boca:</b> De ataque franco y cuerpo medio, con una complejidad de sabores frutales,"
  +      " junto con una ligera astringencia y un retrogusto prolongado <br>"
  +    "</div>"
  +  "</div>"
  +  "<div id='wine_marriage_container'>"
  +    "<div id='wine_marriage_header' class='wine_header'>"
  +      "Maridaje"
  +    "</div>"
  +    "<div id='wine_marriage_txt' class='wine_txt'>"
  +      "Ideal como aperitivo, para acompañar pescados y mariscos,"
  +      " así como carnes blancas y pastas <br>"
  +      "<br>"
  +      "Temperatura de servicio de 16º C."
  +    "</div>"
  +  "</div>"
  +  "<div id='wine_corrections' class='wine_txt'>"
  +    "Vino sin correcciones químicas"
  +  "</div>"
  +"</div>"
  ;

  document.getElementById("main_wine_container").innerHTML = "";
  document.getElementById("main_wine_container").innerHTML = parabola_info;
  document.getElementById('main_wine_container').scrollIntoView({ behavior: 'smooth', block: 'end' });
}

function palabra(){

  var palabra_info = ""
  +"<div class='main_bottle_container'>"
  +  "<img src='images/palabraMain.png' class='main_bottle_container' alt='' >"
  +"</div>"
  +"<div id='text_wine_container'>"
  +  "<div id='main_wine_name'>"
  +    "Palabra"
  +  "</div>"
  +  "<div id='wine_tech_container'>"
  +    "<div id='wine_tech_header' class='wine_header'>"
  +      "Ficha técnica"
  +    "</div>"
  +    "<div id='wine_tech_txt' class='wine_txt'>"
  +      "<b>Clasificación:</b> Tinto <br>"
  +      "<b>Región:</b> San Antonio de las Minas, Valle de Guadalupe <br>"
  +      "<b>Añejamiento:</b> 12 meses en barrica de roble blanco <br>"
  +      "<b>Variedad:</b> Zinfandel 70%, Tmpranillo 15% y Barbera 15% <br>"
  +      "<b>Cosecha:</b> 2015 <br>"
  +    "</div>"
  +  "</div>"
  +  "<div id='wine_notes_container'>"
  +    "<div id='wine_notes_header' class='wine_header'>"
  +      "Nota de cata"
  +    "</div>"
  +    "<div id='wine_notes_txt' class='wine_txt'>"
  +      "<b>Vista:</b> De color morado intenso, y algúnos brillos violáceos en el ribete <br>"
  +      "<b>Nariz:</b> Recuerda a la ciruela, la frambuesa, y a la vainilla,"
  +      " sobre un fondo a regaliz y cacao<br>"
  +      "<b>Boca:</b> Decuerpo medio, presenta una acidez balanceada en boca,"
  +      " así como un final astringente y un retrogusto prolongado <br>"
  +    "</div>"
  +  "</div>"
  +  "<div id='wine_marriage_container'>"
  +    "<div id='wine_marriage_header' class='wine_header'>"
  +      "Maridaje"
  +    "</div>"
  +    "<div id='wine_marriage_txt' class='wine_txt'>"
  +      "Ideal para acompañar platillos de la cocina mexicana, con algunas notas picantes,"
  +      " tales como chiles en nogada, cochinita pibil, gorditas de chicharron y birria <br>"
  +      "<br>"
  +      "Temperatura de servicio de 16º C."
  +    "</div>"
  +  "</div>"
  +  "<div id='wine_corrections' class='wine_txt'>"
  +    "Vino sin correcciones químicas"
  +  "</div>"
  +"</div>"
  ;

  document.getElementById("main_wine_container").innerHTML = "";
  document.getElementById("main_wine_container").innerHTML = palabra_info;
  document.getElementById('main_wine_container').scrollIntoView({ behavior: 'smooth', block: 'end' });
}

function homenaje(){

  var homenaje_info = ""
  +"<div class='main_bottle_container'>"
  +  "<img src='images/homenajeMain.png' class='main_bottle_container' alt='' >"
  +"</div>"
  +"<div id='text_wine_container'>"
  +  "<div id='main_wine_name'>"
  +    "Homenaje"
  +  "</div>"
  +  "<div id='wine_tech_container'>"
  +    "<div id='wine_tech_header' class='wine_header'>"
  +      "Ficha técnica"
  +    "</div>"
  +    "<div id='wine_tech_txt' class='wine_txt'>"
  +      "<b>Clasificación:</b> Tinto <br>"
  +      "<b>Región:</b> San Antonio de las Minas, Valle de Guadalupe <br>"
  +      "<b>Añejamiento:</b> 12 meses en barrica de roble blanco <br>"
  +      "<b>Variedad:</b> Cabernet Franc 40%, Cabernet Sauvignon 40% y Merlot 20% <br>"
  +      "<b>Cosecha:</b> 2015 <br>"
  +    "</div>"
  +  "</div>"
  +  "<div id='wine_notes_container'>"
  +    "<div id='wine_notes_header' class='wine_header'>"
  +      "Nota de cata"
  +    "</div>"
  +    "<div id='wine_notes_txt' class='wine_txt'>"
  +      "<b>Vista:</b> De color rojo rubí con algúnos brillos violáceos en el ribete <br>"
  +      "<b>Nariz:</b> Aromas intensos que recuerdan a las frutas maduras como el higo"
  +      " y la ciruela, así como algunas notas a tabaco, jamaica y chiles secos <br>"
  +      "<b>Boca:</b> De ataque franco y cuerpo medio, con una complejidad aromática"
  +      " frutal, junto con una ligera astringencia y un retrogusto prolongado <br>"
  +    "</div>"
  +  "</div>"
  +  "<div id='wine_marriage_container'>"
  +    "<div id='wine_marriage_header' class='wine_header'>"
  +      "Maridaje"
  +    "</div>"
  +    "<div id='wine_marriage_txt' class='wine_txt'>"
  +      "Ideal para acompañar todo tipo de pastas y pizzas, carnes frias,"
  +      " quesos curados de intensidad media y alta, así como carnes rojas <br>"
  +      "<br>"
  +      "Temperatura de servicio de 16º C."
  +    "</div>"
  +  "</div>"
  +  "<div id='wine_corrections' class='wine_txt'>"
  +    "Vino sin correcciones químicas"
  +  "</div>"
  +"</div>"
  ;

  document.getElementById("main_wine_container").innerHTML = "";
  document.getElementById("main_wine_container").innerHTML = homenaje_info;
  document.getElementById('main_wine_container').scrollIntoView({ behavior: 'smooth', block: 'end' });
}

function retorno(){

  var retorno_info = ""
  +"<div class='main_bottle_container'>"
  +  "<img src='images/retornoMain.png' class='main_bottle_container' alt='' >"
  +"</div>"
  +"<div id='text_wine_container'>"
  +  "<div id='main_wine_name'>"
  +    "Retorno"
  +  "</div>"
  +  "<div id='wine_tech_container'>"
  +    "<div id='wine_tech_header' class='wine_header'>"
  +      "Ficha técnica"
  +    "</div>"
  +    "<div id='wine_tech_txt' class='wine_txt'>"
  +      "<b>Clasificación:</b> Tinto <br>"
  +      "<b>Región:</b> San Antonio de las Minas, Valle de Guadalupe <br>"
  +      "<b>Añejamiento:</b> 24 meses en barrica de roble blanco <br>"
  +      "<b>Variedad:</b> Grenache 90% y syrah 10% <br>"
  +      "<b>Cosecha:</b> 2015 <br>"
  +    "</div>"
  +  "</div>"
  +  "<div id='wine_notes_container'>"
  +    "<div id='wine_notes_header' class='wine_header'>"
  +      "Nota de cata"
  +    "</div>"
  +    "<div id='wine_notes_txt' class='wine_txt'>"
  +      "<b>Vista:</b> De color rojo rubí intenso con algunas notas naranjas en el ribete <br>"
  +      "<b>Nariz:</b> Aromas de frutos rojos como, cereza y frambuesa, sobre un fondo a café,"
  +      " caramelo, regalliz, madera y tabaco <br>"
  +      "<b>Boca:</b> De cuerpo robusto, acidez balanceada,"
  +      " astringencia maedia y un retrogusto frutal muy prolongado <br>"
  +    "</div>"
  +  "</div>"
  +  "<div id='wine_marriage_container'>"
  +    "<div id='wine_marriage_header' class='wine_header'>"
  +      "Maridaje"
  +    "</div>"
  +    "<div id='wine_marriage_txt' class='wine_txt'>"
  +      "Ideal para acompañar estofados de cordero y res,"
  +      " cortes de carne, quesos de intensidad alta y chocolate amargo <br>"
  +      "<br>"
  +      "Temperatura de servicio de 16º C."
  +    "</div>"
  +  "</div>"
  +  "<div id='wine_corrections' class='wine_txt'>"
  +    "Vino sin correcciones químicas"
  +  "</div>"
  +"</div>"
  ;

  document.getElementById("main_wine_container").innerHTML = "";
  document.getElementById("main_wine_container").innerHTML = retorno_info;
  document.getElementById('main_wine_container').scrollIntoView({ behavior: 'smooth', block: 'end' });
}

function decada(){

  var decada_info = ""
  +"<div class='main_bottle_container'>"
  +  "<img src='images/decadaMain.png' class='main_bottle_container' alt='' >"
  +"</div>"
  +"<div id='text_wine_container'>"
  +  "<div id='main_wine_name'>"
  +    "Década"
  +  "</div>"
  +  "<div id='wine_tech_container'>"
  +    "<div id='wine_tech_header' class='wine_header'>"
  +      "Ficha técnica"
  +    "</div>"
  +    "<div id='wine_tech_txt' class='wine_txt'>"
  +      "<b>Clasificación:</b> Tinto <br>"
  +      "<b>Región:</b> San Antonio de las Minas, Valle de Guadalupe <br>"
  +      "<b>Añejamiento:</b> 36 meses en barricas de roble blanco y 24 meses en botella<br>"
  +      "<b>Variedad:</b> Nebbiolo 100% <br>"
  +      "<b>Cosecha:</b> 2013 <br>"
  +    "</div>"
  +  "</div>"
  +  "<div id='wine_notes_container'>"
  +    "<div id='wine_notes_header' class='wine_header'>"
  +      "Nota de cata"
  +    "</div>"
  +    "<div id='wine_notes_txt' class='wine_txt'>"
  +      "<b>Vista:</b> De color morado intenso con tonos rubí en el ribete <br>"
  +      "<b>Nariz:</b> Aromas de frutos maduros como el higo y la ciruela,"
  +      " acompañados de cacao, café, dulce de leche, miel de maple y tabaco <br>"
  +      "<b>Boca:</b> De cuerpo robusto, intenso y balanceado con un retrogusto"
  +      " agradable y muy prolongado <br>"
  +    "</div>"
  +  "</div>"
  +  "<div id='wine_marriage_container'>"
  +    "<div id='wine_marriage_header' class='wine_header'>"
  +      "Maridaje"
  +    "</div>"
  +    "<div id='wine_marriage_txt' class='wine_txt'>"
  +      "Ideal para acompañar estofados de cordero y res, cortes de carne,"
  +      " quesos de intensidad alta y chocolate amargo <br>"
  +      "<br>"
  +      "Temperatura de servicio de 16º C."
  +    "</div>"
  +  "</div>"
  +  "<div id='wine_corrections' class='wine_txt'>"
  +    "Vino sin correcciones químicas"
  +  "</div>"
  +"</div>"
  ;

  document.getElementById("main_wine_container").innerHTML = "";
  document.getElementById("main_wine_container").innerHTML = decada_info;
  document.getElementById('main_wine_container').scrollIntoView({ behavior: 'smooth', block: 'end' });
}


function parabolaBlancoExpand(){

  var parabola_blanco_info_expand = ""
  +"<div id='text_wine_container'>"
  +  "<div id='wine_tech_container'>"
  +    "<div id='wine_tech_header' class='wine_header'>"
  +      "Ficha técnica"
  +    "</div>"
  +    "<div id='wine_tech_txt' class='wine_txt'>"
  +      "<b>Clasificación:</b> Blanco <br>"
  +      "<b>Región:</b> San Antonio de las Minas, Valle de Guadalupe <br>"
  +      "<b>Añejamiento:</b> Fermentado y reposado en tanques de acero inoxidable <br>"
  +      "<b>Variedad:</b> Chenin Blanc <br>"
  +      "<b>Cosecha:</b> 2017 <br>"
  +    "</div>"
  +  "</div>"
  +  "<div id='wine_notes_container'>"
  +    "<div id='wine_notes_header' class='wine_header'>"
  +      "Nota de cata"
  +    "</div>"
  +    "<div id='wine_notes_txt' class='wine_txt'>"
  +      "<b>Vista:</b> De color amarillo paja con brillos dorados y verdes en el ribete <br>"
  +      "<b>Nariz:</b> Aromas a flores blancas y cítricos, entre los que destacan"
  +      " la toronja y limón amarillo <br>"
  +      "<b>Boca:</b> Ligero y agradable, con un ataque franco y una acidez  balanceada"
  +      " acompañada de sabores frutales en el retrogusto  <br>"
  +    "</div>"
  +  "</div>"
  +  "<div id='wine_marriage_container'>"
  +    "<div id='wine_marriage_header' class='wine_header'>"
  +      "Maridaje"
  +    "</div>"
  +    "<div id='wine_marriage_txt' class='wine_txt'>"
  +      "Ideal  para armonizar todo tipo de pescados, pastas"
  +      " cremosas, pizzas y quesos de intensidad media. <br>"
  +      "<br>"
  +      "Temperatura de servicio de 8º a 10º C."
  +    "</div>"
  +  "</div>"
  +  "<div id='wine_corrections' class='wine_txt'>"
  +    "Vino sin correcciones químicas"
  +  "</div>"
  +"</div>"
  ;

  document.getElementById("parabola_blanco_expand").innerHTML = "";
  document.getElementById("parabola_blanco_expand").innerHTML = parabola_blanco_info_expand;
  document.getElementById("parabola_blanco_expand").scrollIntoView({ behavior: 'smooth', block: 'end' });
}

function teoExpand(){

  var teo_info_expand = ""
  +  "<div id='wine_tech_container'>"
  +    "<div id='wine_tech_header' class='wine_header'>"
  +      "Ficha técnica"
  +    "</div>"
  +    "<div id='wine_tech_txt' class='wine_txt'>"
  +      "<b>Clasificación:</b> Blanco <br>"
  +      "<b>Región:</b> San Antonio de las Minas, Valle de Guadalupe <br>"
  +      "<b>Añejamiento:</b> Reposado 8 meses en barricas de roble blanco <br>"
  +      "<b>Variedad:</b> Chenin Blanc y Chardonay <br>"
  +      "<b>Cosecha:</b> 2016 <br>"
  +    "</div>"
  +  "</div>"
  +  "<div id='wine_notes_container'>"
  +    "<div id='wine_notes_header' class='wine_header'>"
  +      "Nota de cata"
  +    "</div>"
  +    "<div id='wine_notes_txt' class='wine_txt'>"
  +      "<b>Vista:</b> De color amarillo paja con brillos verdes en el ribete <br>"
  +      "<b>Nariz:</b> Aromas que recuerdan a la piña, guayaba, durazno y la miel,"
  +      " sobre un fondo a pan tostado, madera y mantequilla <br>"
  +      "<b>Boca:</b> Cuerpo medio con una acidez balanceada y un retrogusto de"
  +      " frutas tropicales con notas a cacao <br>"
  +    "</div>"
  +  "</div>"
  +  "<div id='wine_marriage_container'>"
  +    "<div id='wine_marriage_header' class='wine_header'>"
  +      "Maridaje"
  +    "</div>"
  +    "<div id='wine_marriage_txt' class='wine_txt'>"
  +      "Ideal como aperitivo, para acompañar pescados y mariscos,"
  +      " quesos de intensidad media, pastas cremosas y pizza <br>"
  +      "<br>"
  +      "Temperatura de servicio de 8º a 10º C."
  +    "</div>"
  +  "</div>"
  +  "<div id='wine_corrections' class='wine_txt'>"
  +    "Vino sin correcciones químicas"
  +  "</div>"
  +"</div>"
  ;

  document.getElementById("teo_expand").innerHTML = "";
  document.getElementById("teo_expand").innerHTML = teo_info_expand;
  document.getElementById("teo_expand").scrollIntoView({ behavior: 'smooth', block: 'end' });
}

function piluchasExpand(){

  var piluchas_info_expand = ""
  +  "<div id='wine_tech_container'>"
  +    "<div id='wine_tech_header' class='wine_header'>"
  +      "Ficha técnica"
  +    "</div>"
  +    "<div id='wine_tech_txt' class='wine_txt'>"
  +      "<b>Clasificación:</b> Rosado <br>"
  +      "<b>Región:</b> San Antonio de las Minas, Valle de Guadalupe <br>"
  +      "<b>Añejamiento:</b> Fermentado y reposado en tanques de acero inoxidable <br>"
  +      "<b>Variedad:</b> Grenache, Barbera, Zinfandel y Tempranillo <br>"
  +      "<b>Cosecha:</b> 2017 <br>"
  +    "</div>"
  +  "</div>"
  +  "<div id='wine_notes_container'>"
  +    "<div id='wine_notes_header' class='wine_header'>"
  +      "Nota de cata"
  +    "</div>"
  +    "<div id='wine_notes_txt' class='wine_txt'>"
  +      "<b>Vista:</b> De color rojo claro con brillos violaceos en el ribete <br>"
  +      "<b>Nariz:</b> Aromas a fresas, toronja, flores de azahar y jazmín <br>"
  +      "<b>Boca:</b> Potente y fresco, con un retrogusto muy prolongado <br>"
  +    "</div>"
  +  "</div>"
  +  "<div id='wine_marriage_container'>"
  +    "<div id='wine_marriage_header' class='wine_header'>"
  +      "Maridaje"
  +    "</div>"
  +    "<div id='wine_marriage_txt' class='wine_txt'>"
  +      "Ideal como aperitivo, para acompañar pescados y mariscos,"
  +      " así como carnes blancas y pastas <br>"
  +      "<br>"
  +      "Temperatura de servicio de 8º a 10º C."
  +    "</div>"
  +  "</div>"
  +  "<div id='wine_corrections' class='wine_txt'>"
  +    "Vino sin correcciones químicas"
  +  "</div>"
  +"</div>"
  ;

  document.getElementById("piluchas_expand").innerHTML = "";
  document.getElementById("piluchas_expand").innerHTML = piluchas_info_expand;
  document.getElementById("piluchas_expand").scrollIntoView({ behavior: 'smooth', block: 'end' });
}

function parabolaExpand(){

  var parabola_info_expand = ""
  +  "<div id='wine_tech_container'>"
  +    "<div id='wine_tech_header' class='wine_header'>"
  +      "Ficha técnica"
  +    "</div>"
  +    "<div id='wine_tech_txt' class='wine_txt'>"
  +      "<b>Clasificación:</b> Tinto <br>"
  +      "<b>Región:</b> San Antonio de las Minas, Valle de Guadalupe <br>"
  +      "<b>Añejamiento:</b> 6 meses en barrica de roble blanco <br>"
  +      "<b>Variedad:</b> Tempranillo 50% y Barbera 50% <br>"
  +      "<b>Cosecha:</b> 2016 <br>"
  +    "</div>"
  +  "</div>"
  +  "<div id='wine_notes_container'>"
  +    "<div id='wine_notes_header' class='wine_header'>"
  +      "Nota de cata"
  +    "</div>"
  +    "<div id='wine_notes_txt' class='wine_txt'>"
  +      "<b>Vista:</b> De color rojorubí con algúnos brillos violáceos en el ribete <br>"
  +      "<b>Nariz:</b> Aromas que recuerdan la fruta madura, como las fresas y las frambuesas,"
  +      " así como algunas notas a tabaco, café cacao y madera <br>"
  +      "<b>Boca:</b> De ataque franco y cuerpo medio, con una complejidad de sabores frutales,"
  +      " junto con una ligera astringencia y un retrogusto prolongado <br>"
  +    "</div>"
  +  "</div>"
  +  "<div id='wine_marriage_container'>"
  +    "<div id='wine_marriage_header' class='wine_header'>"
  +      "Maridaje"
  +    "</div>"
  +    "<div id='wine_marriage_txt' class='wine_txt'>"
  +      "Ideal como aperitivo, para acompañar pescados y mariscos,"
  +      " así como carnes blancas y pastas <br>"
  +      "<br>"
  +      "Temperatura de servicio de 16º C."
  +    "</div>"
  +  "</div>"
  +  "<div id='wine_corrections' class='wine_txt'>"
  +    "Vino sin correcciones químicas"
  +  "</div>"
  +"</div>"
  ;

  document.getElementById("parabola_expand").innerHTML = "";
  document.getElementById("parabola_expand").innerHTML = parabola_info_expand;
  document.getElementById("parabola_expand").scrollIntoView({ behavior: 'smooth', block: 'end' });
}

function palabraExpand(){

  var palabra_info_expand = ""
  +  "<div id='wine_tech_container'>"
  +    "<div id='wine_tech_header' class='wine_header'>"
  +      "Ficha técnica"
  +    "</div>"
  +    "<div id='wine_tech_txt' class='wine_txt'>"
  +      "<b>Clasificación:</b> Tinto <br>"
  +      "<b>Región:</b> San Antonio de las Minas, Valle de Guadalupe <br>"
  +      "<b>Añejamiento:</b> 12 meses en barrica de roble blanco <br>"
  +      "<b>Variedad:</b> Zinfandel 70%, Tmpranillo 15% y Barbera 15% <br>"
  +      "<b>Cosecha:</b> 2015 <br>"
  +    "</div>"
  +  "</div>"
  +  "<div id='wine_notes_container'>"
  +    "<div id='wine_notes_header' class='wine_header'>"
  +      "Nota de cata"
  +    "</div>"
  +    "<div id='wine_notes_txt' class='wine_txt'>"
  +      "<b>Vista:</b> De color morado intenso, y algúnos brillos violáceos en el ribete <br>"
  +      "<b>Nariz:</b> Recuerda a la ciruela, la frambuesa, y a la vainilla,"
  +      " sobre un fondo a regaliz y cacao<br>"
  +      "<b>Boca:</b> Decuerpo medio, presenta una acidez balanceada en boca,"
  +      " así como un final astringente y un retrogusto prolongado <br>"
  +    "</div>"
  +  "</div>"
  +  "<div id='wine_marriage_container'>"
  +    "<div id='wine_marriage_header' class='wine_header'>"
  +      "Maridaje"
  +    "</div>"
  +    "<div id='wine_marriage_txt' class='wine_txt'>"
  +      "Ideal para acompañar platillos de la cocina mexicana, con algunas notas picantes,"
  +      " tales como chiles en nogada, cochinita pibil, gorditas de chicharron y birria <br>"
  +      "<br>"
  +      "Temperatura de servicio de 16º C."
  +    "</div>"
  +  "</div>"
  +  "<div id='wine_corrections' class='wine_txt'>"
  +    "Vino sin correcciones químicas"
  +  "</div>"
  +"</div>"
  ;

  document.getElementById("palabra_expand").innerHTML = "";
  document.getElementById("palabra_expand").innerHTML = palabra_info_expand;
  document.getElementById("palabra_expand").scrollIntoView({ behavior: 'smooth', block: 'end' });
}

function homenajeExpand(){

  var homenaje_info_expand = ""
  +  "<div id='wine_tech_container'>"
  +    "<div id='wine_tech_header' class='wine_header'>"
  +      "Ficha técnica"
  +    "</div>"
  +    "<div id='wine_tech_txt' class='wine_txt'>"
  +      "<b>Clasificación:</b> Tinto <br>"
  +      "<b>Región:</b> San Antonio de las Minas, Valle de Guadalupe <br>"
  +      "<b>Añejamiento:</b> 12 meses en barrica de roble blanco <br>"
  +      "<b>Variedad:</b> Cabernet Franc 40%, Cabernet Sauvignon 40% y Merlot 20% <br>"
  +      "<b>Cosecha:</b> 2015 <br>"
  +    "</div>"
  +  "</div>"
  +  "<div id='wine_notes_container'>"
  +    "<div id='wine_notes_header' class='wine_header'>"
  +      "Nota de cata"
  +    "</div>"
  +    "<div id='wine_notes_txt' class='wine_txt'>"
  +      "<b>Vista:</b> De color rojo rubí con algúnos brillos violáceos en el ribete <br>"
  +      "<b>Nariz:</b> Aromas intensos que recuerdan a las frutas maduras como el higo"
  +      " y la ciruela, así como algunas notas a tabaco, jamaica y chiles secos <br>"
  +      "<b>Boca:</b> De ataque franco y cuerpo medio, con una complejidad aromática"
  +      " frutal, junto con una ligera astringencia y un retrogusto prolongado <br>"
  +    "</div>"
  +  "</div>"
  +  "<div id='wine_marriage_container'>"
  +    "<div id='wine_marriage_header' class='wine_header'>"
  +      "Maridaje"
  +    "</div>"
  +    "<div id='wine_marriage_txt' class='wine_txt'>"
  +      "Ideal para acompañar todo tipo de pastas y pizzas, carnes frias,"
  +      " quesos curados de intensidad media y alta, así como carnes rojas <br>"
  +      "<br>"
  +      "Temperatura de servicio de 16º C."
  +    "</div>"
  +  "</div>"
  +  "<div id='wine_corrections' class='wine_txt'>"
  +    "Vino sin correcciones químicas"
  +  "</div>"
  +"</div>"
  ;

  document.getElementById("homenaje_expand").innerHTML = "";
  document.getElementById("homenaje_expand").innerHTML = homenaje_info_expand;
  document.getElementById("homenaje_expand").scrollIntoView({ behavior: 'smooth', block: 'end' });
}

function retornoExpand(){

  var retorno_info_expand = ""
  +  "<div id='wine_tech_container'>"
  +    "<div id='wine_tech_header' class='wine_header'>"
  +      "Ficha técnica"
  +    "</div>"
  +    "<div id='wine_tech_txt' class='wine_txt'>"
  +      "<b>Clasificación:</b> Tinto <br>"
  +      "<b>Región:</b> San Antonio de las Minas, Valle de Guadalupe <br>"
  +      "<b>Añejamiento:</b> 24 meses en barrica de roble blanco <br>"
  +      "<b>Variedad:</b> Grenache 90% y syrah 10% <br>"
  +      "<b>Cosecha:</b> 2015 <br>"
  +    "</div>"
  +  "</div>"
  +  "<div id='wine_notes_container'>"
  +    "<div id='wine_notes_header' class='wine_header'>"
  +      "Nota de cata"
  +    "</div>"
  +    "<div id='wine_notes_txt' class='wine_txt'>"
  +      "<b>Vista:</b> De color rojo rubí intenso con algunas notas naranjas en el ribete <br>"
  +      "<b>Nariz:</b> Aromas de frutos rojos como, cereza y frambuesa, sobre un fondo a café,"
  +      " caramelo, regalliz, madera y tabaco <br>"
  +      "<b>Boca:</b> De cuerpo robusto, acidez balanceada,"
  +      " astringencia maedia y un retrogusto frutal muy prolongado <br>"
  +    "</div>"
  +  "</div>"
  +  "<div id='wine_marriage_container'>"
  +    "<div id='wine_marriage_header' class='wine_header'>"
  +      "Maridaje"
  +    "</div>"
  +    "<div id='wine_marriage_txt' class='wine_txt'>"
  +      "Ideal para acompañar estofados de cordero y res,"
  +      " cortes de carne, quesos de intensidad alta y chocolate amargo <br>"
  +      "<br>"
  +      "Temperatura de servicio de 16º C."
  +    "</div>"
  +  "</div>"
  +  "<div id='wine_corrections' class='wine_txt'>"
  +    "Vino sin correcciones químicas"
  +  "</div>"
  +"</div>"
  ;

  document.getElementById("retorno_expand").innerHTML = "";
  document.getElementById("retorno_expand").innerHTML = retorno_info_expand;
  document.getElementById("retorno_expand").scrollIntoView({ behavior: 'smooth', block: 'end' });
}

function decadaExpand(){

  var decada_info_expand = ""
  +  "<div id='wine_tech_container'>"
  +    "<div id='wine_tech_header' class='wine_header'>"
  +      "Ficha técnica"
  +    "</div>"
  +    "<div id='wine_tech_txt' class='wine_txt'>"
  +      "<b>Clasificación:</b> Tinto <br>"
  +      "<b>Región:</b> San Antonio de las Minas, Valle de Guadalupe <br>"
  +      "<b>Añejamiento:</b> 36 meses en barricas de roble blanco y 24 meses en botella<br>"
  +      "<b>Variedad:</b> Nebbiolo 100% <br>"
  +      "<b>Cosecha:</b> 2013 <br>"
  +    "</div>"
  +  "</div>"
  +  "<div id='wine_notes_container'>"
  +    "<div id='wine_notes_header' class='wine_header'>"
  +      "Nota de cata"
  +    "</div>"
  +    "<div id='wine_notes_txt' class='wine_txt'>"
  +      "<b>Vista:</b> De color morado intenso con tonos rubí en el ribete <br>"
  +      "<b>Nariz:</b> Aromas de frutos maduros como el higo y la ciruela,"
  +      " acompañados de cacao, café, dulce de leche, miel de maple y tabaco <br>"
  +      "<b>Boca:</b> De cuerpo robusto, intenso y balanceado con un retrogusto"
  +      " agradable y muy prolongado <br>"
  +    "</div>"
  +  "</div>"
  +  "<div id='wine_marriage_container'>"
  +    "<div id='wine_marriage_header' class='wine_header'>"
  +      "Maridaje"
  +    "</div>"
  +    "<div id='wine_marriage_txt' class='wine_txt'>"
  +      "Ideal para acompañar estofados de cordero y res, cortes de carne,"
  +      " quesos de intensidad alta y chocolate amargo <br>"
  +      "<br>"
  +      "Temperatura de servicio de 16º C."
  +    "</div>"
  +  "</div>"
  +  "<div id='wine_corrections' class='wine_txt'>"
  +    "Vino sin correcciones químicas"
  +  "</div>"
  +"</div>"
  ;

  document.getElementById("decada_expand").innerHTML = "";
  document.getElementById("decada_expand").innerHTML = decada_info_expand;
  document.getElementById("decada_expand").scrollIntoView({ behavior: 'smooth', block: 'end' });
}

function loadPuntosVenta(){

  var puntos_venta_code= ""
  +  "<div class='body_background' id='puntos_venta_background'>"
  +    "<div id='navbar'>"
  +      "<div id='burger_button_container'>"
  +        "<button type='button' class='toggler_btn' data-toggle='collapse' data-target='#mini_navbar' aria-expanded='false' aria-controls='mini_navbar'>"
  +          "<svg version='1.1' id='hamburger_icon' xmlns='http://www.w3.org/2000/svg' xmlns:xlink='http://www.w3.org/1999/xlink' x='0px' y='0px'"
  +              "viewBox='0 0 83.785 64.488' enable-background='new 0 0 83.785 64.488' xml:space='preserve'>"
  +          "<path d='M15.656,19.125H68.13c2.414,0,4.373-1.959,4.373-4.373s-1.959-4.373-4.373-4.373H15.656"
  +            "c-2.414,0-4.373,1.959-4.373,4.373S13.242,19.125,15.656,19.125z M68.13,27.871H15.656c-2.414,0-4.373,1.959-4.373,4.373"
  +            "c0,2.414,1.959,4.373,4.373,4.373H68.13c2.414,0,4.373-1.959,4.373-4.373C72.503,29.83,70.544,27.871,68.13,27.871z M68.13,45.363"
  +            "H15.656c-2.414,0-4.373,1.959-4.373,4.373s1.959,4.373,4.373,4.373H68.13c2.414,0,4.373-1.959,4.373-4.373"
  +            "S70.544,45.363,68.13,45.363z'/>"
  +          "</svg>"
  +      "</div>"
  +      "<div id='nav_options_container'>"
  +        "<div class='nav_options'>"
  +          "<a href='nosotros.html'>"
  +            "Nosotros"
  +         "</a>"
  +        "</div>"
  +        "<div class='nav_options'>"
  +          "<a href='nuestros_vinos.html'>"
  +            "Nuestos Vinos"
  +          "</a>"
  +        "</div>"
  +        "<div id='center_logo_container'>"
  +          "<a href='index.html'>"
  +          "<img src='images/logoBlanco.svg' alt='Logo Vinícola Retorno' id='center_logo'>"
  +          "</a>"
  +        "</div>"
  +        "<div class='nav_options' id='active_nav'>"
  +          "<a href='puntos_venta.html'>"
  +           "Puntos de Venta"
  +          "</a>"
  +        "</div>"
  +        "<div class='nav_options'>"
  +          "<a href='visitanos.html'>"
  +            "Visítanos"
  +          "</a>"
  +        "</div>"
  +      "</div>"
  +      "<div class='collapse' id='mini_navbar'>"
  +        "<div class='option_mini_navbar'>"
  +          "<a href='index.html'>"
  +            "Inicio"
  +          "</a>"
  +        "</div>"
  +        "<div class='option_mini_navbar'>"
  +          "<a href='nosotros.html'>"
  +            "Nosotros"
  +          "</a>"
  +        "</div>"
  +        "<div class='option_mini_navbar'>"
  +          "<a href='nuestros_vinos.html'>"
  +            "Nuestos Vinos"
  +          "</a>"
  +        "</div>"
  +        "<div class='option_mini_navbar' id='active'>"
  +          "<a href='puntos_venta.html'>"
  +            "Puntos de Venta"
  +          "</a>"
  +        "</div>"
  +        "<div class='option_mini_navbar'>"
  +          "<a href='visitanos.html'>"
  +            "Visítanos"
  +          "</a>"
  +        "</div>"
  +      "</div>"
  +    "</div>"
  +    "<div id='sec_mid_image_text'>"
  +     "<div class='mid_image_text_container' id='sec_mid_text'>"
  +      "Puntos de Venta"
  +     "</div>"
  +   "</div>"
  +  "</div>"
  +  "<div id='main_body_container'>"
  +   "<div id='main_body_title'>"
  +    "¿Dónde encontrarnos?"
  +   "</div>"
  +   "<div id='main_body'>"
  +    "<div id='all_sellpoint_container'>"
  +      "<div class='main_sellpoint_container'>"
  +        "<div class='group_sellpoint_text'>"
  +         "Puntos de venta"
  +        "</div>"
  +        "<div class='group_sellpoint_container'>"
  +          "<div class='sellpoint_container'>"
  +            "<div class='sellpoint_logo'>"
  +              "<img src='images/liverpool.png' alt='Logo Liverpool' class='sellpoint_logo'>"
  +            "</div>"
  +            "<div class='sellpoint_name'>"
  +             "Liverpool"
  +            "</div>"
  +          "</div>"
  +          "<div class='sellpoint_container'>"
  +            "<div class='sellpoint_logo'>"
  +              "<img src='images/laContra.png' alt='Logo La Contra' class='sellpoint_logo'>"
  +            "</div>"
  +            "<div class='sellpoint_name'>"
  +             "La Contra"
  +            "</div>"
  +          "</div>"
  +          "<div class='sellpoint_container'>"
  +            "<div class='sellpoint_logo'>"
  +              "<img src='images/cavaTienda.png' alt='Logo Cava Tienda' class='sellpoint_logo'>"
  +            "</div>"
  +            "<div class='sellpoint_name'>"
  +              "Cava Tienda"
  +            "</div>"
  +          "</div>"
  +          "<div class='sellpoint_container'>"
  +            "<div class='sellpoint_logo'>"
  +              "<img src='images/vidMexicana.png' alt='Logo Vid Mexicana' class='sellpoint_logo'>"
  +            "</div>"
  +            "<div class='sellpoint_name'>"
  +              "Vid Mexicana"
  +            "</div>"
  +          "</div>"
  +          "<div class='sellpoint_container'>"
  +            "<div class='sellpoint_logo'>"
  +              "<img src='images/jengibre.png' alt='Logo Jengibre' class='sellpoint_logo'>"
  +            "</div>"
  +            "<div class='sellpoint_name'>"
  +              "Jengibre"
  +            "</div>"
  +          "</div>"
  +          "<div class='sellpoint_container'>"
  +            "<div class='sellpoint_logo'>"
  +              "<img src='images/limosneros.png' alt='Logo Limosneros' class='sellpoint_logo'>"
  +            "</div>"
  +            "<div class='sellpoint_name'>"
  +              "Limosneros"
  +            "</div>"
  +          "</div>"
  +          "<div class='sellpoint_container'>"
  +            "<div class='sellpoint_logo'>"
  +              "<img src='images/wineCellar.png' alt='Logo Wine Cellar' class='sellpoint_logo'>"
  +            "</div>"
  +            "<div class='sellpoint_name'>"
  +               "Wine Cellar"
  +            "</div>"
  +          "</div>"
  +          "<div class='sellpoint_container'>"
  +            "<div class='sellpoint_logo'>"
  +              "<img src='images/luncheta.png' alt='Logo Luncheta' class='sellpoint_logo'>"
  +            "</div>"
  +            "<div class='sellpoint_name'>"
  +              "Luncheta"
  +            "</div>"
  +          "</div>"
  +          "<div class='sellpoint_container'>"
  +            "<div class='sellpoint_logo'>"
  +              "<img src='images/vinata.png' alt='Logo La Vinata' class='sellpoint_logo'>"
  +            "</div>"
  +            "<div class='sellpoint_name'>"
  +              "La Vinata"
  +            "</div>"
  +          "</div>"
  +          "<div class='sellpoint_container'>"
  +            "<div class='sellpoint_logo'>"
  +              "<img src='images/vinario.png' alt='Logo Vinario' class='sellpoint_logo'>"
  +            "</div>"
  +            "<div class='sellpoint_name'>"
  +              "Vinario"
  +            "</div>"
  +          "</div>"
  +        "</div>"
  +      "</div>"
  +      "<div class='main_sellpoint_container'>"
  +        "<div class='group_sellpoint_text'>"
  +          "Puntos de consumo"
  +        "</div>"
  +        "<div class='group_sellpoint_container'>"
  +          "<div class='sellpoint_container'>"
  +            "<div class='sellpoint_logo'>"
  +              "<img src='images/presidente.png' alt='Logo Hotel Presidente' class='sellpoint_logo'>"
  +            "</div>"
  +            "<div class='sellpoint_name'>"
  +              "Hotel Presidente"
  +            "</div>"
  +          "</div>"
  +          "<div class='sellpoint_container'>"
  +            "<div class='sellpoint_logo'>"
  +              "<img src='images/cavaMia.png' alt='Logo Cava Mía' class='sellpoint_logo'>"
  +            "</div>"
  +            "<div class='sellpoint_name'>"
  +              "Cava Mía"
  +            "</div>"
  +          "</div>"
  +          "<div class='sellpoint_container'>"
  +            "<div class='sellpoint_logo'>"
  +              "<img src='images/ophelia.png' alt='Logo Ophelia' class='sellpoint_logo'>"
  +            "</div>"
  +            "<div class='sellpoint_name'>"
  +              "Ophelia"
  +            "</div>"
  +          "</div>"
  +          "<div class='sellpoint_container'>"
  +            "<div class='sellpoint_logo'>"
  +              "<img src='images/campanario.png' alt='Logo El Campanario' class='sellpoint_logo'>"
  +            "</div>"
  +            "<div class='sellpoint_name'>"
  +              "El Campanario"
  +            "</div>"
  +          "</div>"
  +          "<div class='sellpoint_container'>"
  +            "<div class='sellpoint_logo'>"
  +              "<img src='images/carlota.png' alt='Logo Hotel Carlota' class='sellpoint_logo'>"
  +            "</div>"
  +            "<div class='sellpoint_name'>"
  +              "Hotel Carlota"
  +            "</div>"
  +          "</div>"
  +          "<div class='sellpoint_container'>"
  +            "<div class='sellpoint_logo'>"
  +              "<img src='images/maglen.png' alt='Logo Maglén' class='sellpoint_logo'>"
  +            "</div>"
  +            "<div class='sellpoint_name'>"
  +              "Maglén"
  +            "</div>"
  +          "</div>"
  +          "<div class='sellpoint_container'>"
  +            "<div class='sellpoint_logo'>"
  +              "<img src='images/frida.png' alt='Logo Casa Frida' class='sellpoint_logo'>"
  +            "</div>"
  +            "<div class='sellpoint_name'>"
  +              "Casa Frida"
  +            "</div>"
  +          "</div>"
  +          "<div class='sellpoint_container'>"
  +            "<div class='sellpoint_logo'>"
  +              "<img src='images/cafeRegina.png' alt='Logo Café Regina' class='sellpoint_logo'>"
  +            "</div>"
  +            "<div class='sellpoint_name'>"
  +             "Café Regina"
  +            "</div>"
  +          "</div>"
  +          "<div class='sellpoint_container'>"
  +            "<div class='sellpoint_logo'>"
  +              "<img src='images/quercus.png' alt='Logo Quercus' class='sellpoint_logo'>"
  +            "</div>"
  +            "<div class='sellpoint_name'>"
  +              "Quercus"
  +            "</div>"
  +          "</div>"
  +          "<div class='sellpoint_container'>"
  +            "<div class='sellpoint_logo'>"
  +              "<img src='images/coralMarina.png' alt='Logo Hotel Coral y Marina' class='sellpoint_logo'>"
  +            "</div>"
  +            "<div class='sellpoint_name'>"
  +              "Hotel Coral y Marina"
  +            "</div>"
  +          "</div>"
  +          "<div class='sellpoint_container'>"
  +            "<div class='sellpoint_logo'>"
  +              "<img src='images/jengibre.png' alt='Logo Jengibre' class='sellpoint_logo'>"
  +            "</div>"
  +            "<div class='sellpoint_name'>"
  +              "Jengibre"
  +            "</div>"
  +          "</div>"
  +          "<div class='sellpoint_container'>"
  +            "<div class='sellpoint_logo'>"
  +              "<img src='images/limosneros.png' alt='Logo Limosneros' class='sellpoint_logo'>"
  +            "</div>"
  +            "<div class='sellpoint_name'>"
  +              "Limosneros"
  +            "</div>"
  +          "</div>"
  +          "<div class='sellpoint_container'>"
  +            "<div class='sellpoint_logo'>"
  +              "<img src='images/luncheta.png' alt='Logo Luncheta' class='sellpoint_logo'>"
  +            "</div>"
  +            "<div class='sellpoint_name'>"
  +              "Luncheta"
  +            "</div>"
  +          "</div>"
  +        "</div>"
  +      "</div>"
  +    "</div>"
  +  "</div>"
  +  "<div id='footer'>"
  +    "<div id='footer_options_container'>"
  +      "<div class='footer_option' id='left_option'>"
  +        "<a href='index.html'>"
  +          "<img src='images/logoBlanco.svg' alt='Logo Vinícola Retorno' id='logo_footer'>"
  +        "</a>"
  +        "<div id='vinicola_legal'>"
  +          "<a href='index.html'>"
  +           "© Copyright <br>"
  +            "Vinícola Retorno S.A. de C.V."
  +          "</a>"
  +        "</div>"
  +      "</div>"
  +      "<div class='footer_option' id='center_option'>"
  +        "<div class='footer_headline'>"
  +          "<a href='visitanos.html'>"
  +            "Contactanos"
  +          "</a>"
  +        "</div>"
  +        "<div class='info_cities'>"
  +          "CDMX"
  +        "</div>"
  +          "<a href='tel:+525555284733'>"
  +            "55-28-47-33"
  +          "</a>"
  +        "<div class='info_cities'>"
  +          "Valle de Guadalupe"
  +        "</div>"
  +          "<a href='tel:+5216461519247'>"
  +            "646-151-92-47<br>"
  +          "</a>"
  +          "<a href='mailto:info@vinicolaretorno.com'>"
  +            "info@vinicolaretorno.com"
  +          "</a>"
  +      "</div>"
  +      "<div class='footer_option' id='center_option'>"
  +        "<div class='footer_headline'>"
  +          "<a href='visitanos.html'>"
  +            "Visítanos"
  +          "</a>"
  +        "</div>"
  +        "<div id='info_visit'>"
  +          "Todos los dias <br>"
  +          "11:00 AM - 5:00 PM <br>"
  +          "<div id='info_address'>"
  +            "Santos Degollado #161, San Antonio de las Minas,"
  +            " C.P. 22766, Ensenada, BC."
  +          "</div>"
  +        "</div>"
  +      "</div>"
  +      "<div class='footer_option' id='right_option'>"
  +        "<div class='footer_headline'>"
  +          "<a href='visitanos.html'>"
  +            "Síguenos"
  +          "</a>"
  +        "</div>"
  +        "<div id='social_media_container'>"
  +          "<div class='social_media'>"
  +            "<a href='https://www.facebook.com/vinicolaretorno/'>"
  +              "<img src='images/facebook.svg' alt='Facebook Vinícola Retorno' class='social_media'>"
  +            "</a>"
  +          "</div>"
  +          "<div class='social_media'>"
  +            "<a href='https://twitter.com/vinicolaretorno'>"
  +              "<img src='images/twitter.svg' alt='Twitter Vinícola Retorno' class='social_media'>"
  +            "</a>"
  +          "</div>"
  +          "<div class='social_media'>"
  +            "<a href='https://www.instagram.com/vinicolaretorno/'>"
  +              "<img src='images/instagram.svg' alt='Instagram Vinícola Retorno' class='social_media'>"
  +            "</a>"
  +          "</div>"
  +        "</div>"
  +      "</div>"
  +    "</div>"
  +  "</div>"
;
  document.getElementById("puntos_venta_page").innerHTML = "";
  document.getElementById("puntos_venta_page").innerHTML = puntos_venta_code;
}

function loadVisitanos(){

  var visitanos_code= ""
  +  "<div class='body_background' id='visitanos_background'>"
  +    "<div id='navbar'>"
  +      "<div id='burger_button_container'>"
  +        "<button type='button' class='toggler_btn' data-toggle='collapse' data-target='#mini_navbar' aria-expanded='false' aria-controls='mini_navbar'>"
  +          "<svg version='1.1' id='hamburger_icon' xmlns='http://www.w3.org/2000/svg' xmlns:xlink='http://www.w3.org/1999/xlink' x='0px' y='0px'"
  +              "viewBox='0 0 83.785 64.488' enable-background='new 0 0 83.785 64.488' xml:space='preserve'>"
  +          "<path d='M15.656,19.125H68.13c2.414,0,4.373-1.959,4.373-4.373s-1.959-4.373-4.373-4.373H15.656"
  +            "c-2.414,0-4.373,1.959-4.373,4.373S13.242,19.125,15.656,19.125z M68.13,27.871H15.656c-2.414,0-4.373,1.959-4.373,4.373"
  +            "c0,2.414,1.959,4.373,4.373,4.373H68.13c2.414,0,4.373-1.959,4.373-4.373C72.503,29.83,70.544,27.871,68.13,27.871z M68.13,45.363"
  +            "H15.656c-2.414,0-4.373,1.959-4.373,4.373s1.959,4.373,4.373,4.373H68.13c2.414,0,4.373-1.959,4.373-4.373"
  +            "S70.544,45.363,68.13,45.363z'/>"
  +          "</svg>"
  +      "</div>"
  +      "<div id='nav_options_container'>"
  +        "<div class='nav_options'>"
  +          "<a href='nosotros.html'>"
  +            "Nosotros"
  +         "</a>"
  +        "</div>"
  +        "<div class='nav_options'>"
  +          "<a href='nuestros_vinos.html'>"
  +            "Nuestos Vinos"
  +          "</a>"
  +        "</div>"
  +        "<div id='center_logo_container'>"
  +          "<a href='index.html'>"
  +          "<img src='images/logoBlanco.svg' alt='Logo Vinícola Retorno' id='center_logo'>"
  +          "</a>"
  +        "</div>"
  +        "<div class='nav_options'>"
  +          "<a href='puntos_venta.html'>"
  +           "Puntos de Venta"
  +          "</a>"
  +        "</div>"
  +        "<div class='nav_options' id='active_nav'>"
  +          "<a href='visitanos.html'>"
  +            "Visítanos"
  +          "</a>"
  +        "</div>"
  +      "</div>"
  +      "<div class='collapse' id='mini_navbar'>"
  +        "<div class='option_mini_navbar'>"
  +          "<a href='index.html'>"
  +            "Inicio"
  +          "</a>"
  +        "</div>"
  +        "<div class='option_mini_navbar'>"
  +          "<a href='nosotros.html'>"
  +            "Nosotros"
  +          "</a>"
  +        "</div>"
  +        "<div class='option_mini_navbar'>"
  +          "<a href='nuestros_vinos.html'>"
  +            "Nuestos Vinos"
  +          "</a>"
  +        "</div>"
  +        "<div class='option_mini_navbar'>"
  +          "<a href='puntos_venta.html'>"
  +            "Puntos de Venta"
  +          "</a>"
  +        "</div>"
  +        "<div class='option_mini_navbar' id='active'>"
  +          "<a href='visitanos.html'>"
  +            "Visítanos"
  +          "</a>"
  +        "</div>"
  +      "</div>"
  +    "</div>"
  +    "<div id='sec_mid_image_text'>"
  +      "<div class='mid_image_text_container' id='sec_mid_text'>"
  +        "Visítanos"
  +      "</div>"
  +    "</div>"
  +  "</div>"
  +    "<div id='main_body_container'>"
  +      "<div id='main_body_title'>"
  +        "Ven a conocernos"
  +      "</div>"
  +      "<div id='main_body'>"
  +        "<div class='visit_container' id='visit_top'>"
  +          "<div class='visit_headline'>"
  +            "Visítanos todos los dias"
  +          "</div>"
  +            "11:00 AM - 5:00 PM"
  +            "<br>"
  +            "<a href='tel:+5216461519247'>"
  +              "646-151-92-47<br>"
  +            "</a>"
  +            "<a id='adress_main'>"
  +              "Santos Degollado #161, San Antonio de las Minas,"
  +              " C.P. 22766, Ensenada, BC."
  +            "</a>"
  +            "<a id='adress_link' onclick='mapsApp()'>"
  +              "Santos Degollado #161, San Antonio de las Minas,"
  +              " C.P. 22766, Ensenada, BC."
  +            "</a>"
  +            "<div id='location_icon_container' onclick='mapsApp()'>"
  +              "<img src='images/locationIcon.png' alt='Ubicación Vinícola Retorno' class='location_icon'>"
  +            "</div>"
  +        "</div>"
  +        "<div id='map_container_main'>"
  +          "<iframe src='https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d108408.53005652729!2d-116.69846464818215!3d31.88576348251703!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x80d8edb5a54c7d7b%3A0xa378da87e61997cf!2sVin%C3%ADcola+Retorno!5e0!3m2!1sen!2smx!4v1544807769893' width='100%' height='500' frameborder='0' style='border:0' allowfullscreen>"
  +          "</iframe>"
  +        "</div>"
  +        "<div id='map_container_link' onclick='mapsApp()'>"
  +          "<iframe src='https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d108408.53005652729!2d-116.69846464818215!3d31.88576348251703!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x80d8edb5a54c7d7b%3A0xa378da87e61997cf!2sVin%C3%ADcola+Retorno!5e0!3m2!1sen!2smx!4v1544807769893' width='100%' height='500' frameborder='0' style='border:0' allowfullscreen>"
  +          "</iframe>"
  +        "</div>"
  +        "<div class='visit_container' id='visit_bottom'>"
  +          "<div class='visit_headline'>"
  +            "Contacto en la CDMX"
  +          "</div>"
  +          "<a href='tel:+525555284733'>"
  +            "55-28-47-33"
  +          "</a>"
  +          "<br>"
  +          "<a href='mailto:info@vinicolaretorno.com'>"
  +            "info@vinicolaretorno.com"
  +          "</a>"
  +        "</div>"
  +      "</div>"
  +  "<div id='footer'>"
  +    "<div id='footer_options_container'>"
  +      "<div class='footer_option' id='left_option'>"
  +        "<a href='index.html'>"
  +          "<img src='images/logoBlanco.svg' alt='Logo Vinícola Retorno' id='logo_footer'>"
  +        "</a>"
  +        "<div id='vinicola_legal'>"
  +          "<a href='index.html'>"
  +           "© Copyright <br>"
  +            "Vinícola Retorno S.A. de C.V."
  +          "</a>"
  +        "</div>"
  +      "</div>"
  +      "<div class='footer_option' id='center_option'>"
  +        "<div class='footer_headline'>"
  +          "<a href='visitanos.html'>"
  +            "Contactanos"
  +          "</a>"
  +        "</div>"
  +        "<div class='info_cities'>"
  +          "CDMX"
  +        "</div>"
  +          "<a href='tel:+525555284733'>"
  +            "55-28-47-33"
  +          "</a>"
  +        "<div class='info_cities'>"
  +          "Valle de Guadalupe"
  +        "</div>"
  +          "<a href='tel:+5216461519247'>"
  +            "646-151-92-47<br>"
  +          "</a>"
  +          "<a href='mailto:info@vinicolaretorno.com'>"
  +            "info@vinicolaretorno.com"
  +          "</a>"
  +      "</div>"
  +      "<div class='footer_option' id='center_option'>"
  +        "<div class='footer_headline'>"
  +          "<a href='visitanos.html'>"
  +            "Visítanos"
  +          "</a>"
  +        "</div>"
  +        "<div id='info_visit'>"
  +          "Todos los dias <br>"
  +          "11:00 AM - 5:00 PM <br>"
  +          "<div id='info_address'>"
  +            "Santos Degollado #161, San Antonio de las Minas,"
  +            " C.P. 22766, Ensenada, BC."
  +          "</div>"
  +        "</div>"
  +      "</div>"
  +      "<div class='footer_option' id='right_option'>"
  +        "<div class='footer_headline'>"
  +          "<a href='visitanos.html'>"
  +            "Síguenos"
  +          "</a>"
  +        "</div>"
  +        "<div id='social_media_container'>"
  +          "<div class='social_media'>"
  +            "<a href='https://www.facebook.com/vinicolaretorno/'>"
  +              "<img src='images/facebook.svg' alt='Facebook Vinícola Retorno' class='social_media'>"
  +            "</a>"
  +          "</div>"
  +          "<div class='social_media'>"
  +            "<a href='https://twitter.com/vinicolaretorno'>"
  +              "<img src='images/twitter.svg' alt='Twitter Vinícola Retorno' class='social_media'>"
  +            "</a>"
  +          "</div>"
  +          "<div class='social_media'>"
  +            "<a href='https://www.instagram.com/vinicolaretorno/'>"
  +              "<img src='images/instagram.svg' alt='Instagram Vinícola Retorno' class='social_media'>"
  +            "</a>"
  +          "</div>"
  +        "</div>"
  +      "</div>"
  +    "</div>"
  +  "</div>"
;
  document.getElementById("visitanos_page").innerHTML = "";
  document.getElementById("visitanos_page").innerHTML = visitanos_code;
}

function mapsApp() {
  if /* if we're on iOS, open in Apple Maps */
    ((navigator.platform.indexOf("iPhone") != -1) ||
     (navigator.platform.indexOf("iPod") != -1) ||
     (navigator.platform.indexOf("iPad") != -1))
    window.open("maps://goo.gl/maps/i4ayPiigYf22");

  else /* else use Google */
    window.open("https://goo.gl/maps/i4ayPiigYf22");
}
