
function parabolaBlanco(){

  var parabola_blanco_info = ""
  +"<div class='main_bottle_container'>"
  +  "<img src='images/parabolaBlancoMain.png' class='main_bottle_container' alt='' >"
  +"</div>"
  +"<div id='text_wine_container'>"
  +  "<div id='main_wine_name'>"
  +    "Parábola Blanco"
  +  "</div>"
  +  "<div id='wine_tech_container'>"
  +    "<div id='wine_tech_header' class='wine_header'>"
  +      "Ficha técnica"
  +    "</div>"
  +    "<div id='wine_tech_txt' class='wine_txt'>"
  +      "<b>Clasificación:</b> Blanco <br>"
  +      "<b>Región:</b> San Antonio de las Minas, Valle de Guadalupe <br>"
  +      "<b>Añejamiento:</b> 12 meses en barrica de roble blanco <br>"
  +      "<b>Variedad:</b> Cabernet Franc 40%, Cabernet Sauvignon 40% y Merlot 20% <br>"
  +      "<b>Cosecha:</b> 2015 <br>"
  +    "</div>"
  +  "</div>"
  +  "<div id='wine_notes_container'>"
  +    "<div id='wine_notes_header' class='wine_header'>"
  +      "Nota de cata"
  +    "</div>"
  +    "<div id='wine_notes_txt' class='wine_txt'>"
  +      "<b>Vista:</b> De color rojo rubí con algúnos brillos violáceos en el ribete <br>"
  +      "<b>Nariz:</b> Aromas intensos que recuerdan a las frutas maduras como el higo"
  +      " y la ciruela, así como algunas notas a tabaco, jamaica y chiles secos <br>"
  +      "<b>Boca:</b> De ataque franco y cuerpo medio, con una complejidad aromática"
  +      " frutal, junto con una ligera astringencia y un retrogusto prolongado <br>"
  +    "</div>"
  +  "</div>"
  +  "<div id='wine_marriage_container'>"
  +    "<div id='wine_marriage_header' class='wine_header'>"
  +      "Maridaje"
  +    "</div>"
  +    "<div id='wine_marriage_txt' class='wine_txt'>"
  +      "Ideal para acompañar todo tipo de pastas y pizzas, carnes frias,"
  +      " quesos curados de intensidad media y alta, así como carnes rojas <br>"
  +      "<br>"
  +      "Temperatura de servicio de 16º C."
  +    "</div>"
  +  "</div>"
  +  "<div id='wine_corrections' class='wine_txt'>"
  +    "Vino sin correcciones químicas"
  +  "</div>"
  +"</div>"
  ;

  document.getElementById("main_wine_container").innerHTML = "";
  document.getElementById("main_wine_container").innerHTML = parabola_blanco_info;
}

function teo(){

  var teo_info = ""
  +"<div class='main_bottle_container'>"
  +  "<img src='images/teoMain.png' class='main_bottle_container' alt='' >"
  +"</div>"
  +"<div id='text_wine_container'>"
  +  "<div id='main_wine_name'>"
  +    "TeO"
  +  "</div>"
  +  "<div id='wine_tech_container'>"
  +    "<div id='wine_tech_header' class='wine_header'>"
  +      "Ficha técnica"
  +    "</div>"
  +    "<div id='wine_tech_txt' class='wine_txt'>"
  +      "<b>Clasificación:</b> Blanco <br>"
  +      "<b>Región:</b> San Antonio de las Minas, Valle de Guadalupe <br>"
  +      "<b>Añejamiento:</b> 12 meses en barrica de roble blanco <br>"
  +      "<b>Variedad:</b> Cabernet Franc 40%, Cabernet Sauvignon 40% y Merlot 20% <br>"
  +      "<b>Cosecha:</b> 2015 <br>"
  +    "</div>"
  +  "</div>"
  +  "<div id='wine_notes_container'>"
  +    "<div id='wine_notes_header' class='wine_header'>"
  +      "Nota de cata"
  +    "</div>"
  +    "<div id='wine_notes_txt' class='wine_txt'>"
  +      "<b>Vista:</b> De color rojo rubí con algúnos brillos violáceos en el ribete <br>"
  +      "<b>Nariz:</b> Aromas intensos que recuerdan a las frutas maduras como el higo"
  +      " y la ciruela, así como algunas notas a tabaco, jamaica y chiles secos <br>"
  +      "<b>Boca:</b> De ataque franco y cuerpo medio, con una complejidad aromática"
  +      " frutal, junto con una ligera astringencia y un retrogusto prolongado <br>"
  +    "</div>"
  +  "</div>"
  +  "<div id='wine_marriage_container'>"
  +    "<div id='wine_marriage_header' class='wine_header'>"
  +      "Maridaje"
  +    "</div>"
  +    "<div id='wine_marriage_txt' class='wine_txt'>"
  +      "Ideal para acompañar todo tipo de pastas y pizzas, carnes frias,"
  +      " quesos curados de intensidad media y alta, así como carnes rojas <br>"
  +      "<br>"
  +      "Temperatura de servicio de 16º C."
  +    "</div>"
  +  "</div>"
  +  "<div id='wine_corrections' class='wine_txt'>"
  +    "Vino sin correcciones químicas"
  +  "</div>"
  +"</div>"
  ;

  document.getElementById("main_wine_container").innerHTML = "";
  document.getElementById("main_wine_container").innerHTML = teo_info;
}

function piluchas(){

  var piluchas_info = ""
  +"<div class='main_bottle_container'>"
  +  "<img src='images/piluchasMain.png' class='main_bottle_container' alt='' >"
  +"</div>"
  +"<div id='text_wine_container'>"
  +  "<div id='main_wine_name'>"
  +    "Piluchas"
  +  "</div>"
  +  "<div id='wine_tech_container'>"
  +    "<div id='wine_tech_header' class='wine_header'>"
  +      "Ficha técnica"
  +    "</div>"
  +    "<div id='wine_tech_txt' class='wine_txt'>"
  +      "<b>Clasificación:</b> Rosado <br>"
  +      "<b>Región:</b> San Antonio de las Minas, Valle de Guadalupe <br>"
  +      "<b>Añejamiento:</b> 12 meses en barrica de roble blanco <br>"
  +      "<b>Variedad:</b> Cabernet Franc 40%, Cabernet Sauvignon 40% y Merlot 20% <br>"
  +      "<b>Cosecha:</b> 2015 <br>"
  +    "</div>"
  +  "</div>"
  +  "<div id='wine_notes_container'>"
  +    "<div id='wine_notes_header' class='wine_header'>"
  +      "Nota de cata"
  +    "</div>"
  +    "<div id='wine_notes_txt' class='wine_txt'>"
  +      "<b>Vista:</b> De color rojo rubí con algúnos brillos violáceos en el ribete <br>"
  +      "<b>Nariz:</b> Aromas intensos que recuerdan a las frutas maduras como el higo"
  +      " y la ciruela, así como algunas notas a tabaco, jamaica y chiles secos <br>"
  +      "<b>Boca:</b> De ataque franco y cuerpo medio, con una complejidad aromática"
  +      " frutal, junto con una ligera astringencia y un retrogusto prolongado <br>"
  +    "</div>"
  +  "</div>"
  +  "<div id='wine_marriage_container'>"
  +    "<div id='wine_marriage_header' class='wine_header'>"
  +      "Maridaje"
  +    "</div>"
  +    "<div id='wine_marriage_txt' class='wine_txt'>"
  +      "Ideal para acompañar todo tipo de pastas y pizzas, carnes frias,"
  +      " quesos curados de intensidad media y alta, así como carnes rojas <br>"
  +      "<br>"
  +      "Temperatura de servicio de 16º C."
  +    "</div>"
  +  "</div>"
  +  "<div id='wine_corrections' class='wine_txt'>"
  +    "Vino sin correcciones químicas"
  +  "</div>"
  +"</div>"
  ;

  document.getElementById("main_wine_container").innerHTML = "";
  document.getElementById("main_wine_container").innerHTML = piluchas_info;
}

function parabola(){

  var parabola_info = ""
  +"<div class='main_bottle_container'>"
  +  "<img src='images/parabolaMain.png' class='main_bottle_container' alt='' >"
  +"</div>"
  +"<div id='text_wine_container'>"
  +  "<div id='main_wine_name'>"
  +    "Parábola"
  +  "</div>"
  +  "<div id='wine_tech_container'>"
  +    "<div id='wine_tech_header' class='wine_header'>"
  +      "Ficha técnica"
  +    "</div>"
  +    "<div id='wine_tech_txt' class='wine_txt'>"
  +      "<b>Clasificación:</b> Tinto <br>"
  +      "<b>Región:</b> San Antonio de las Minas, Valle de Guadalupe <br>"
  +      "<b>Añejamiento:</b> 12 meses en barrica de roble blanco <br>"
  +      "<b>Variedad:</b> Cabernet Franc 40%, Cabernet Sauvignon 40% y Merlot 20% <br>"
  +      "<b>Cosecha:</b> 2015 <br>"
  +    "</div>"
  +  "</div>"
  +  "<div id='wine_notes_container'>"
  +    "<div id='wine_notes_header' class='wine_header'>"
  +      "Nota de cata"
  +    "</div>"
  +    "<div id='wine_notes_txt' class='wine_txt'>"
  +      "<b>Vista:</b> De color rojo rubí con algúnos brillos violáceos en el ribete <br>"
  +      "<b>Nariz:</b> Aromas intensos que recuerdan a las frutas maduras como el higo"
  +      " y la ciruela, así como algunas notas a tabaco, jamaica y chiles secos <br>"
  +      "<b>Boca:</b> De ataque franco y cuerpo medio, con una complejidad aromática"
  +      " frutal, junto con una ligera astringencia y un retrogusto prolongado <br>"
  +    "</div>"
  +  "</div>"
  +  "<div id='wine_marriage_container'>"
  +    "<div id='wine_marriage_header' class='wine_header'>"
  +      "Maridaje"
  +    "</div>"
  +    "<div id='wine_marriage_txt' class='wine_txt'>"
  +      "Ideal para acompañar todo tipo de pastas y pizzas, carnes frias,"
  +      " quesos curados de intensidad media y alta, así como carnes rojas <br>"
  +      "<br>"
  +      "Temperatura de servicio de 16º C."
  +    "</div>"
  +  "</div>"
  +  "<div id='wine_corrections' class='wine_txt'>"
  +    "Vino sin correcciones químicas"
  +  "</div>"
  +"</div>"
  ;

  document.getElementById("main_wine_container").innerHTML = "";
  document.getElementById("main_wine_container").innerHTML = parabola_info;
}

function palabra(){

  var palabra_info = ""
  +"<div class='main_bottle_container'>"
  +  "<img src='images/palabraMain.png' class='main_bottle_container' alt='' >"
  +"</div>"
  +"<div id='text_wine_container'>"
  +  "<div id='main_wine_name'>"
  +    "Palabra"
  +  "</div>"
  +  "<div id='wine_tech_container'>"
  +    "<div id='wine_tech_header' class='wine_header'>"
  +      "Ficha técnica"
  +    "</div>"
  +    "<div id='wine_tech_txt' class='wine_txt'>"
  +      "<b>Clasificación:</b> Tinto <br>"
  +      "<b>Región:</b> San Antonio de las Minas, Valle de Guadalupe <br>"
  +      "<b>Añejamiento:</b> 12 meses en barrica de roble blanco <br>"
  +      "<b>Variedad:</b> Cabernet Franc 40%, Cabernet Sauvignon 40% y Merlot 20% <br>"
  +      "<b>Cosecha:</b> 2015 <br>"
  +    "</div>"
  +  "</div>"
  +  "<div id='wine_notes_container'>"
  +    "<div id='wine_notes_header' class='wine_header'>"
  +      "Nota de cata"
  +    "</div>"
  +    "<div id='wine_notes_txt' class='wine_txt'>"
  +      "<b>Vista:</b> De color rojo rubí con algúnos brillos violáceos en el ribete <br>"
  +      "<b>Nariz:</b> Aromas intensos que recuerdan a las frutas maduras como el higo"
  +      " y la ciruela, así como algunas notas a tabaco, jamaica y chiles secos <br>"
  +      "<b>Boca:</b> De ataque franco y cuerpo medio, con una complejidad aromática"
  +      " frutal, junto con una ligera astringencia y un retrogusto prolongado <br>"
  +    "</div>"
  +  "</div>"
  +  "<div id='wine_marriage_container'>"
  +    "<div id='wine_marriage_header' class='wine_header'>"
  +      "Maridaje"
  +    "</div>"
  +    "<div id='wine_marriage_txt' class='wine_txt'>"
  +      "Ideal para acompañar todo tipo de pastas y pizzas, carnes frias,"
  +      " quesos curados de intensidad media y alta, así como carnes rojas <br>"
  +      "<br>"
  +      "Temperatura de servicio de 16º C."
  +    "</div>"
  +  "</div>"
  +  "<div id='wine_corrections' class='wine_txt'>"
  +    "Vino sin correcciones químicas"
  +  "</div>"
  +"</div>"
  ;

  document.getElementById("main_wine_container").innerHTML = "";
  document.getElementById("main_wine_container").innerHTML = palabra_info;
}

function homenaje(){

  var homenaje_info = ""
  +"<div class='main_bottle_container'>"
  +  "<img src='images/homenajeMain.png' class='main_bottle_container' alt='' >"
  +"</div>"
  +"<div id='text_wine_container'>"
  +  "<div id='main_wine_name'>"
  +    "Homenaje"
  +  "</div>"
  +  "<div id='wine_tech_container'>"
  +    "<div id='wine_tech_header' class='wine_header'>"
  +      "Ficha técnica"
  +    "</div>"
  +    "<div id='wine_tech_txt' class='wine_txt'>"
  +      "<b>Clasificación:</b> Tinto <br>"
  +      "<b>Región:</b> San Antonio de las Minas, Valle de Guadalupe <br>"
  +      "<b>Añejamiento:</b> 12 meses en barrica de roble blanco <br>"
  +      "<b>Variedad:</b> Cabernet Franc 40%, Cabernet Sauvignon 40% y Merlot 20% <br>"
  +      "<b>Cosecha:</b> 2015 <br>"
  +    "</div>"
  +  "</div>"
  +  "<div id='wine_notes_container'>"
  +    "<div id='wine_notes_header' class='wine_header'>"
  +      "Nota de cata"
  +    "</div>"
  +    "<div id='wine_notes_txt' class='wine_txt'>"
  +      "<b>Vista:</b> De color rojo rubí con algúnos brillos violáceos en el ribete <br>"
  +      "<b>Nariz:</b> Aromas intensos que recuerdan a las frutas maduras como el higo"
  +      " y la ciruela, así como algunas notas a tabaco, jamaica y chiles secos <br>"
  +      "<b>Boca:</b> De ataque franco y cuerpo medio, con una complejidad aromática"
  +      " frutal, junto con una ligera astringencia y un retrogusto prolongado <br>"
  +    "</div>"
  +  "</div>"
  +  "<div id='wine_marriage_container'>"
  +    "<div id='wine_marriage_header' class='wine_header'>"
  +      "Maridaje"
  +    "</div>"
  +    "<div id='wine_marriage_txt' class='wine_txt'>"
  +      "Ideal para acompañar todo tipo de pastas y pizzas, carnes frias,"
  +      " quesos curados de intensidad media y alta, así como carnes rojas <br>"
  +      "<br>"
  +      "Temperatura de servicio de 16º C."
  +    "</div>"
  +  "</div>"
  +  "<div id='wine_corrections' class='wine_txt'>"
  +    "Vino sin correcciones químicas"
  +  "</div>"
  +"</div>"
  ;

  document.getElementById("main_wine_container").innerHTML = "";
  document.getElementById("main_wine_container").innerHTML = homenaje_info;
}

function retorno(){

  var retorno_info = ""
  +"<div class='main_bottle_container'>"
  +  "<img src='images/retornoMain.png' class='main_bottle_container' alt='' >"
  +"</div>"
  +"<div id='text_wine_container'>"
  +  "<div id='main_wine_name'>"
  +    "Retorno"
  +  "</div>"
  +  "<div id='wine_tech_container'>"
  +    "<div id='wine_tech_header' class='wine_header'>"
  +      "Ficha técnica"
  +    "</div>"
  +    "<div id='wine_tech_txt' class='wine_txt'>"
  +      "<b>Clasificación:</b> Tinto <br>"
  +      "<b>Región:</b> San Antonio de las Minas, Valle de Guadalupe <br>"
  +      "<b>Añejamiento:</b> 12 meses en barrica de roble blanco <br>"
  +      "<b>Variedad:</b> Cabernet Franc 40%, Cabernet Sauvignon 40% y Merlot 20% <br>"
  +      "<b>Cosecha:</b> 2015 <br>"
  +    "</div>"
  +  "</div>"
  +  "<div id='wine_notes_container'>"
  +    "<div id='wine_notes_header' class='wine_header'>"
  +      "Nota de cata"
  +    "</div>"
  +    "<div id='wine_notes_txt' class='wine_txt'>"
  +      "<b>Vista:</b> De color rojo rubí con algúnos brillos violáceos en el ribete <br>"
  +      "<b>Nariz:</b> Aromas intensos que recuerdan a las frutas maduras como el higo"
  +      " y la ciruela, así como algunas notas a tabaco, jamaica y chiles secos <br>"
  +      "<b>Boca:</b> De ataque franco y cuerpo medio, con una complejidad aromática"
  +      " frutal, junto con una ligera astringencia y un retrogusto prolongado <br>"
  +    "</div>"
  +  "</div>"
  +  "<div id='wine_marriage_container'>"
  +    "<div id='wine_marriage_header' class='wine_header'>"
  +      "Maridaje"
  +    "</div>"
  +    "<div id='wine_marriage_txt' class='wine_txt'>"
  +      "Ideal para acompañar todo tipo de pastas y pizzas, carnes frias,"
  +      " quesos curados de intensidad media y alta, así como carnes rojas <br>"
  +      "<br>"
  +      "Temperatura de servicio de 16º C."
  +    "</div>"
  +  "</div>"
  +  "<div id='wine_corrections' class='wine_txt'>"
  +    "Vino sin correcciones químicas"
  +  "</div>"
  +"</div>"
  ;

  document.getElementById("main_wine_container").innerHTML = "";
  document.getElementById("main_wine_container").innerHTML = retorno_info;
}

function decada(){

  var decada_info = ""
  +"<div class='main_bottle_container'>"
  +  "<img src='images/decadaMain.png' class='main_bottle_container' alt='' >"
  +"</div>"
  +"<div id='text_wine_container'>"
  +  "<div id='main_wine_name'>"
  +    "Década"
  +  "</div>"
  +  "<div id='wine_tech_container'>"
  +    "<div id='wine_tech_header' class='wine_header'>"
  +      "Ficha técnica"
  +    "</div>"
  +    "<div id='wine_tech_txt' class='wine_txt'>"
  +      "<b>Clasificación:</b> Tinto <br>"
  +      "<b>Región:</b> San Antonio de las Minas, Valle de Guadalupe <br>"
  +      "<b>Añejamiento:</b> 12 meses en barrica de roble blanco <br>"
  +      "<b>Variedad:</b> Cabernet Franc 40%, Cabernet Sauvignon 40% y Merlot 20% <br>"
  +      "<b>Cosecha:</b> 2015 <br>"
  +    "</div>"
  +  "</div>"
  +  "<div id='wine_notes_container'>"
  +    "<div id='wine_notes_header' class='wine_header'>"
  +      "Nota de cata"
  +    "</div>"
  +    "<div id='wine_notes_txt' class='wine_txt'>"
  +      "<b>Vista:</b> De color rojo rubí con algúnos brillos violáceos en el ribete <br>"
  +      "<b>Nariz:</b> Aromas intensos que recuerdan a las frutas maduras como el higo"
  +      " y la ciruela, así como algunas notas a tabaco, jamaica y chiles secos <br>"
  +      "<b>Boca:</b> De ataque franco y cuerpo medio, con una complejidad aromática"
  +      " frutal, junto con una ligera astringencia y un retrogusto prolongado <br>"
  +    "</div>"
  +  "</div>"
  +  "<div id='wine_marriage_container'>"
  +    "<div id='wine_marriage_header' class='wine_header'>"
  +      "Maridaje"
  +    "</div>"
  +    "<div id='wine_marriage_txt' class='wine_txt'>"
  +      "Ideal para acompañar todo tipo de pastas y pizzas, carnes frias,"
  +      " quesos curados de intensidad media y alta, así como carnes rojas <br>"
  +      "<br>"
  +      "Temperatura de servicio de 16º C."
  +    "</div>"
  +  "</div>"
  +  "<div id='wine_corrections' class='wine_txt'>"
  +    "Vino sin correcciones químicas"
  +  "</div>"
  +"</div>"
  ;

  document.getElementById("main_wine_container").innerHTML = "";
  document.getElementById("main_wine_container").innerHTML = decada_info;
}
