
function parabolaBlanco(){

  var parabola_blanco_info = ""
  +"<div class='main_bottle_container'>"
  +  "<img src='images/parabolaBlancoMain.png' class='main_bottle_container' alt='' >"
  +"</div>"
  +"<div id='text_wine_container'>"
  +  "<div id='main_wine_name'>"
  +    "Parábola Blanco"
  +  "</div>"
  +  "<div id='wine_tech_container'>"
  +    "<div id='wine_tech_header' class='wine_header'>"
  +      "Ficha técnica"
  +    "</div>"
  +    "<div id='wine_tech_txt' class='wine_txt'>"
  +      "<b>Clasificación:</b> Blanco <br>"
  +      "<b>Región:</b> San Antonio de las Minas, Valle de Guadalupe <br>"
  +      "<b>Añejamiento:</b> Fermentado y reposado en tanques de acero inoxidable <br>"
  +      "<b>Variedad:</b> Chenin Blanc <br>"
  +      "<b>Cosecha:</b> 2017 <br>"
  +    "</div>"
  +  "</div>"
  +  "<div id='wine_notes_container'>"
  +    "<div id='wine_notes_header' class='wine_header'>"
  +      "Nota de cata"
  +    "</div>"
  +    "<div id='wine_notes_txt' class='wine_txt'>"
  +      "<b>Vista:</b> De color amarillo paja con brillos dorados y verdes en el ribete <br>"
  +      "<b>Nariz:</b> Aromas a flores blancas y cítricos, entre los que destacan"
  +      " la toronja y limón amarillo <br>"
  +      "<b>Boca:</b> Ligero y agradable, con un ataque franco y una acidez  balanceada"
  +      " acompañada de sabores frutales en el retrogusto  <br>"
  +    "</div>"
  +  "</div>"
  +  "<div id='wine_marriage_container'>"
  +    "<div id='wine_marriage_header' class='wine_header'>"
  +      "Maridaje"
  +    "</div>"
  +    "<div id='wine_marriage_txt' class='wine_txt'>"
  +      "Ideal  para armonizar todo tipo de pescados, pastas"
  +      " cremosas, pizzas y quesos de intensidad media. <br>"
  +      "<br>"
  +      "Temperatura de servicio de 8º a 10º C."
  +    "</div>"
  +  "</div>"
  +  "<div id='wine_corrections' class='wine_txt'>"
  +    "Vino sin correcciones químicas"
  +  "</div>"
  +"</div>"
  ;

  document.getElementById("main_wine_container").innerHTML = "";
  document.getElementById("main_wine_container").innerHTML = parabola_blanco_info;
  document.getElementById('main_wine_container').scrollIntoView({ behavior: 'smooth', block: 'end' });
}

function teo(){

  var teo_info = ""
  +"<div class='main_bottle_container'>"
  +  "<img src='images/teoMain.png' class='main_bottle_container' alt='' >"
  +"</div>"
  +"<div id='text_wine_container'>"
  +  "<div id='main_wine_name'>"
  +    "TeO"
  +  "</div>"
  +  "<div id='wine_tech_container'>"
  +    "<div id='wine_tech_header' class='wine_header'>"
  +      "Ficha técnica"
  +    "</div>"
  +    "<div id='wine_tech_txt' class='wine_txt'>"
  +      "<b>Clasificación:</b> Blanco <br>"
  +      "<b>Región:</b> San Antonio de las Minas, Valle de Guadalupe <br>"
  +      "<b>Añejamiento:</b> Reposado 8 meses en barricas de roble blanco <br>"
  +      "<b>Variedad:</b> Chenin Blanc y Chardonay <br>"
  +      "<b>Cosecha:</b> 2016 <br>"
  +    "</div>"
  +  "</div>"
  +  "<div id='wine_notes_container'>"
  +    "<div id='wine_notes_header' class='wine_header'>"
  +      "Nota de cata"
  +    "</div>"
  +    "<div id='wine_notes_txt' class='wine_txt'>"
  +      "<b>Vista:</b> De color amarillo paja con brillos verdes en el ribete <br>"
  +      "<b>Nariz:</b> Aromas que recuerdan a la piña, guayaba, durazno y la miel,"
  +      " sobre un fondo a pan tostado, madera y mantequilla <br>"
  +      "<b>Boca:</b> Cuerpo medio con una acidez balanceada y un retrogusto de"
  +      " frutas tropicales con notas a cacao <br>"
  +    "</div>"
  +  "</div>"
  +  "<div id='wine_marriage_container'>"
  +    "<div id='wine_marriage_header' class='wine_header'>"
  +      "Maridaje"
  +    "</div>"
  +    "<div id='wine_marriage_txt' class='wine_txt'>"
  +      "Ideal como aperitivo, para acompañar pescados y mariscos,"
  +      " quesos de intensidad media, pastas cremosas y pizza <br>"
  +      "<br>"
  +      "Temperatura de servicio de 8º a 10º C."
  +    "</div>"
  +  "</div>"
  +  "<div id='wine_corrections' class='wine_txt'>"
  +    "Vino sin correcciones químicas"
  +  "</div>"
  +"</div>"
  ;

  document.getElementById("main_wine_container").innerHTML = "";
  document.getElementById("main_wine_container").innerHTML = teo_info;
  document.getElementById('main_wine_container').scrollIntoView({ behavior: 'smooth', block: 'end' });
}

function piluchas(){

  var piluchas_info = ""
  +"<div class='main_bottle_container'>"
  +  "<img src='images/piluchasMain.png' class='main_bottle_container' alt='' >"
  +"</div>"
  +"<div id='text_wine_container'>"
  +  "<div id='main_wine_name'>"
  +    "Piluchas"
  +  "</div>"
  +  "<div id='wine_tech_container'>"
  +    "<div id='wine_tech_header' class='wine_header'>"
  +      "Ficha técnica"
  +    "</div>"
  +    "<div id='wine_tech_txt' class='wine_txt'>"
  +      "<b>Clasificación:</b> Rosado <br>"
  +      "<b>Región:</b> San Antonio de las Minas, Valle de Guadalupe <br>"
  +      "<b>Añejamiento:</b> Fermentado y reposado en tanques de acero inoxidable <br>"
  +      "<b>Variedad:</b> Grenache, Barbera, Zinfandel y Tempranillo <br>"
  +      "<b>Cosecha:</b> 2017 <br>"
  +    "</div>"
  +  "</div>"
  +  "<div id='wine_notes_container'>"
  +    "<div id='wine_notes_header' class='wine_header'>"
  +      "Nota de cata"
  +    "</div>"
  +    "<div id='wine_notes_txt' class='wine_txt'>"
  +      "<b>Vista:</b> De color rojo claro con brillos violaceos en el ribete <br>"
  +      "<b>Nariz:</b> Aromas a fresas, toronja, flores de azahar y jazmín <br>"
  +      "<b>Boca:</b> Potente y fresco, con un retrogusto muy prolongado <br>"
  +    "</div>"
  +  "</div>"
  +  "<div id='wine_marriage_container'>"
  +    "<div id='wine_marriage_header' class='wine_header'>"
  +      "Maridaje"
  +    "</div>"
  +    "<div id='wine_marriage_txt' class='wine_txt'>"
  +      "Ideal como aperitivo, para acompañar pescados y mariscos,"
  +      " así como carnes blancas y pastas <br>"
  +      "<br>"
  +      "Temperatura de servicio de 8º a 10º C."
  +    "</div>"
  +  "</div>"
  +  "<div id='wine_corrections' class='wine_txt'>"
  +    "Vino sin correcciones químicas"
  +  "</div>"
  +"</div>"
  ;

  document.getElementById("main_wine_container").innerHTML = "";
  document.getElementById("main_wine_container").innerHTML = piluchas_info;
  document.getElementById('main_wine_container').scrollIntoView({ behavior: 'smooth', block: 'end' });
}

function parabola(){

  var parabola_info = ""
  +"<div class='main_bottle_container'>"
  +  "<img src='images/parabolaMain.png' class='main_bottle_container' alt='' >"
  +"</div>"
  +"<div id='text_wine_container'>"
  +  "<div id='main_wine_name'>"
  +    "Parábola"
  +  "</div>"
  +  "<div id='wine_tech_container'>"
  +    "<div id='wine_tech_header' class='wine_header'>"
  +      "Ficha técnica"
  +    "</div>"
  +    "<div id='wine_tech_txt' class='wine_txt'>"
  +      "<b>Clasificación:</b> Tinto <br>"
  +      "<b>Región:</b> San Antonio de las Minas, Valle de Guadalupe <br>"
  +      "<b>Añejamiento:</b> 6 meses en barrica de roble blanco <br>"
  +      "<b>Variedad:</b> Tempranillo 50% y Barbera 50% <br>"
  +      "<b>Cosecha:</b> 2016 <br>"
  +    "</div>"
  +  "</div>"
  +  "<div id='wine_notes_container'>"
  +    "<div id='wine_notes_header' class='wine_header'>"
  +      "Nota de cata"
  +    "</div>"
  +    "<div id='wine_notes_txt' class='wine_txt'>"
  +      "<b>Vista:</b> De color rojorubí con algúnos brillos violáceos en el ribete <br>"
  +      "<b>Nariz:</b> Aromas que recuerdan la fruta madura, como las fresas y las frambuesas,"
  +      " así como algunas notas a tabaco, café cacao y madera <br>"
  +      "<b>Boca:</b> De ataque franco y cuerpo medio, con una complejidad de sabores frutales,"
  +      " junto con una ligera astringencia y un retrogusto prolongado <br>"
  +    "</div>"
  +  "</div>"
  +  "<div id='wine_marriage_container'>"
  +    "<div id='wine_marriage_header' class='wine_header'>"
  +      "Maridaje"
  +    "</div>"
  +    "<div id='wine_marriage_txt' class='wine_txt'>"
  +      "Ideal como aperitivo, para acompañar pescados y mariscos,"
  +      " así como carnes blancas y pastas <br>"
  +      "<br>"
  +      "Temperatura de servicio de 16º C."
  +    "</div>"
  +  "</div>"
  +  "<div id='wine_corrections' class='wine_txt'>"
  +    "Vino sin correcciones químicas"
  +  "</div>"
  +"</div>"
  ;

  document.getElementById("main_wine_container").innerHTML = "";
  document.getElementById("main_wine_container").innerHTML = parabola_info;
  document.getElementById('main_wine_container').scrollIntoView({ behavior: 'smooth', block: 'end' });
}

function palabra(){

  var palabra_info = ""
  +"<div class='main_bottle_container'>"
  +  "<img src='images/palabraMain.png' class='main_bottle_container' alt='' >"
  +"</div>"
  +"<div id='text_wine_container'>"
  +  "<div id='main_wine_name'>"
  +    "Palabra"
  +  "</div>"
  +  "<div id='wine_tech_container'>"
  +    "<div id='wine_tech_header' class='wine_header'>"
  +      "Ficha técnica"
  +    "</div>"
  +    "<div id='wine_tech_txt' class='wine_txt'>"
  +      "<b>Clasificación:</b> Tinto <br>"
  +      "<b>Región:</b> San Antonio de las Minas, Valle de Guadalupe <br>"
  +      "<b>Añejamiento:</b> 12 meses en barrica de roble blanco <br>"
  +      "<b>Variedad:</b> Zinfandel 70%, Tmpranillo 15% y Barbera 15% <br>"
  +      "<b>Cosecha:</b> 2015 <br>"
  +    "</div>"
  +  "</div>"
  +  "<div id='wine_notes_container'>"
  +    "<div id='wine_notes_header' class='wine_header'>"
  +      "Nota de cata"
  +    "</div>"
  +    "<div id='wine_notes_txt' class='wine_txt'>"
  +      "<b>Vista:</b> De color morado intenso, y algúnos brillos violáceos en el ribete <br>"
  +      "<b>Nariz:</b> Recuerda a la ciruela, la frambuesa, y a la vainilla,"
  +      " sobre un fondo a regaliz y cacao<br>"
  +      "<b>Boca:</b> Decuerpo medio, presenta una acidez balanceada en boca,"
  +      " así como un final astringente y un retrogusto prolongado <br>"
  +    "</div>"
  +  "</div>"
  +  "<div id='wine_marriage_container'>"
  +    "<div id='wine_marriage_header' class='wine_header'>"
  +      "Maridaje"
  +    "</div>"
  +    "<div id='wine_marriage_txt' class='wine_txt'>"
  +      "Ideal para acompañar platillos de la cocina mexicana, con algunas notas picantes,"
  +      " tales como chiles en nogada, cochinita pibil, gorditas de chicharron y birria <br>"
  +      "<br>"
  +      "Temperatura de servicio de 16º C."
  +    "</div>"
  +  "</div>"
  +  "<div id='wine_corrections' class='wine_txt'>"
  +    "Vino sin correcciones químicas"
  +  "</div>"
  +"</div>"
  ;

  document.getElementById("main_wine_container").innerHTML = "";
  document.getElementById("main_wine_container").innerHTML = palabra_info;
  document.getElementById('main_wine_container').scrollIntoView({ behavior: 'smooth', block: 'end' });
}

function homenaje(){

  var homenaje_info = ""
  +"<div class='main_bottle_container'>"
  +  "<img src='images/homenajeMain.png' class='main_bottle_container' alt='' >"
  +"</div>"
  +"<div id='text_wine_container'>"
  +  "<div id='main_wine_name'>"
  +    "Homenaje"
  +  "</div>"
  +  "<div id='wine_tech_container'>"
  +    "<div id='wine_tech_header' class='wine_header'>"
  +      "Ficha técnica"
  +    "</div>"
  +    "<div id='wine_tech_txt' class='wine_txt'>"
  +      "<b>Clasificación:</b> Tinto <br>"
  +      "<b>Región:</b> San Antonio de las Minas, Valle de Guadalupe <br>"
  +      "<b>Añejamiento:</b> 12 meses en barrica de roble blanco <br>"
  +      "<b>Variedad:</b> Cabernet Franc 40%, Cabernet Sauvignon 40% y Merlot 20% <br>"
  +      "<b>Cosecha:</b> 2015 <br>"
  +    "</div>"
  +  "</div>"
  +  "<div id='wine_notes_container'>"
  +    "<div id='wine_notes_header' class='wine_header'>"
  +      "Nota de cata"
  +    "</div>"
  +    "<div id='wine_notes_txt' class='wine_txt'>"
  +      "<b>Vista:</b> De color rojo rubí con algúnos brillos violáceos en el ribete <br>"
  +      "<b>Nariz:</b> Aromas intensos que recuerdan a las frutas maduras como el higo"
  +      " y la ciruela, así como algunas notas a tabaco, jamaica y chiles secos <br>"
  +      "<b>Boca:</b> De ataque franco y cuerpo medio, con una complejidad aromática"
  +      " frutal, junto con una ligera astringencia y un retrogusto prolongado <br>"
  +    "</div>"
  +  "</div>"
  +  "<div id='wine_marriage_container'>"
  +    "<div id='wine_marriage_header' class='wine_header'>"
  +      "Maridaje"
  +    "</div>"
  +    "<div id='wine_marriage_txt' class='wine_txt'>"
  +      "Ideal para acompañar todo tipo de pastas y pizzas, carnes frias,"
  +      " quesos curados de intensidad media y alta, así como carnes rojas <br>"
  +      "<br>"
  +      "Temperatura de servicio de 16º C."
  +    "</div>"
  +  "</div>"
  +  "<div id='wine_corrections' class='wine_txt'>"
  +    "Vino sin correcciones químicas"
  +  "</div>"
  +"</div>"
  ;

  document.getElementById("main_wine_container").innerHTML = "";
  document.getElementById("main_wine_container").innerHTML = homenaje_info;
  document.getElementById('main_wine_container').scrollIntoView({ behavior: 'smooth', block: 'end' });
}

function retorno(){

  var retorno_info = ""
  +"<div class='main_bottle_container'>"
  +  "<img src='images/retornoMain.png' class='main_bottle_container' alt='' >"
  +"</div>"
  +"<div id='text_wine_container'>"
  +  "<div id='main_wine_name'>"
  +    "Retorno"
  +  "</div>"
  +  "<div id='wine_tech_container'>"
  +    "<div id='wine_tech_header' class='wine_header'>"
  +      "Ficha técnica"
  +    "</div>"
  +    "<div id='wine_tech_txt' class='wine_txt'>"
  +      "<b>Clasificación:</b> Tinto <br>"
  +      "<b>Región:</b> San Antonio de las Minas, Valle de Guadalupe <br>"
  +      "<b>Añejamiento:</b> 24 meses en barrica de roble blanco <br>"
  +      "<b>Variedad:</b> Grenache 90% y syrah 10% <br>"
  +      "<b>Cosecha:</b> 2015 <br>"
  +    "</div>"
  +  "</div>"
  +  "<div id='wine_notes_container'>"
  +    "<div id='wine_notes_header' class='wine_header'>"
  +      "Nota de cata"
  +    "</div>"
  +    "<div id='wine_notes_txt' class='wine_txt'>"
  +      "<b>Vista:</b> De color rojo rubí intenso con algunas notas naranjas en el ribete <br>"
  +      "<b>Nariz:</b> Aromas de frutos rojos como, cereza y frambuesa, sobre un fondo a café,"
  +      " caramelo, regalliz, madera y tabaco <br>"
  +      "<b>Boca:</b> De cuerpo robusto, acidez balanceada,"
  +      " astringencia maedia y un retrogusto frutal muy prolongado <br>"
  +    "</div>"
  +  "</div>"
  +  "<div id='wine_marriage_container'>"
  +    "<div id='wine_marriage_header' class='wine_header'>"
  +      "Maridaje"
  +    "</div>"
  +    "<div id='wine_marriage_txt' class='wine_txt'>"
  +      "Ideal para acompañar estofados de cordero y res,"
  +      " cortes de carne, quesos de intensidad alta y chocolate amargo <br>"
  +      "<br>"
  +      "Temperatura de servicio de 16º C."
  +    "</div>"
  +  "</div>"
  +  "<div id='wine_corrections' class='wine_txt'>"
  +    "Vino sin correcciones químicas"
  +  "</div>"
  +"</div>"
  ;

  document.getElementById("main_wine_container").innerHTML = "";
  document.getElementById("main_wine_container").innerHTML = retorno_info;
  document.getElementById('main_wine_container').scrollIntoView({ behavior: 'smooth', block: 'end' });
}

function decada(){

  var decada_info = ""
  +"<div class='main_bottle_container'>"
  +  "<img src='images/decadaMain.png' class='main_bottle_container' alt='' >"
  +"</div>"
  +"<div id='text_wine_container'>"
  +  "<div id='main_wine_name'>"
  +    "Década"
  +  "</div>"
  +  "<div id='wine_tech_container'>"
  +    "<div id='wine_tech_header' class='wine_header'>"
  +      "Ficha técnica"
  +    "</div>"
  +    "<div id='wine_tech_txt' class='wine_txt'>"
  +      "<b>Clasificación:</b> Tinto <br>"
  +      "<b>Región:</b> San Antonio de las Minas, Valle de Guadalupe <br>"
  +      "<b>Añejamiento:</b> 36 meses en barricas de roble blanco y 24 meses en botella<br>"
  +      "<b>Variedad:</b> Nebbiolo 100% <br>"
  +      "<b>Cosecha:</b> 2013 <br>"
  +    "</div>"
  +  "</div>"
  +  "<div id='wine_notes_container'>"
  +    "<div id='wine_notes_header' class='wine_header'>"
  +      "Nota de cata"
  +    "</div>"
  +    "<div id='wine_notes_txt' class='wine_txt'>"
  +      "<b>Vista:</b> De color morado intenso con tonos rubí en el ribete <br>"
  +      "<b>Nariz:</b> Aromas de frutos maduros como el higo y la ciruela,"
  +      " acompañados de cacao, café, dulce de leche, miel de maple y tabaco <br>"
  +      "<b>Boca:</b> De cuerpo robusto, intenso y balanceado con un retrogusto"
  +      " agradable y muy prolongado <br>"
  +    "</div>"
  +  "</div>"
  +  "<div id='wine_marriage_container'>"
  +    "<div id='wine_marriage_header' class='wine_header'>"
  +      "Maridaje"
  +    "</div>"
  +    "<div id='wine_marriage_txt' class='wine_txt'>"
  +      "Ideal para acompañar estofados de cordero y res, cortes de carne,"
  +      " quesos de intensidad alta y chocolate amargo <br>"
  +      "<br>"
  +      "Temperatura de servicio de 16º C."
  +    "</div>"
  +  "</div>"
  +  "<div id='wine_corrections' class='wine_txt'>"
  +    "Vino sin correcciones químicas"
  +  "</div>"
  +"</div>"
  ;

  document.getElementById("main_wine_container").innerHTML = "";
  document.getElementById("main_wine_container").innerHTML = decada_info;
  document.getElementById('main_wine_container').scrollIntoView({ behavior: 'smooth', block: 'end' });
}
